window.PARTS_CATALOG = [
  {
    "id": "rpi5-16",
    "name": "Raspberry Pi 5 — 16 GB",
    "short": "Główny komputer Kory",
    "category": "Komputery",
    "supplier": "Pi Hut",
    "project": "Kora / VEGA",
    "status": "W drodze",
    "price": "£182.90",
    "accent": "violet",
    "spec": "16 GB RAM • czterordzeniowy CPU • PCIe • 2× MIPI",
    "url": "https://thepihut.com/search?q=Raspberry%20Pi%205%2016GB",
    "youtubePl": "Głównym komputerem robota Kora jest Raspberry Pi 5 z 16 GB pamięci RAM.",
    "youtubeEn": "Kora's main computer is a Raspberry Pi 5 with 16 GB of RAM."
  },
  {
    "id": "ai-hat-2",
    "name": "Raspberry Pi AI HAT+ 2 — Hailo",
    "short": "Akcelerator Hailo do lokalnego przetwarzania modeli",
    "category": "Komputery",
    "supplier": "Pi Hut",
    "project": "Kora / VEGA",
    "status": "W drodze",
    "price": "£130.20*",
    "accent": "violet",
    "spec": "Akcelerator Hailo do obliczeń lokalnych • zestaw z taśmą MIPI 300 mm",
    "url": "https://thepihut.com/search?q=Raspberry%20Pi%20AI%20HAT%2B%202",
    "youtubePl": "Do lokalnego przetwarzania wykorzystuję Raspberry Pi AI HAT+ 2 z akceleratorem Hailo.",
    "youtubeEn": "I use the Raspberry Pi AI HAT+ 2 with a Hailo accelerator for local model processing."
  },
  {
    "id": "xvf3800",
    "name": "ReSpeaker XVF3800 4-Mic Array",
    "short": "Cztery mikrofony i kierunkowe audio",
    "category": "Audio",
    "supplier": "Pi Hut",
    "project": "Kora / VEGA",
    "status": "W drodze",
    "price": "£51.50",
    "accent": "pink",
    "spec": "4 mikrofony • XMOS XVF3800 • redukcja echa i szumu",
    "url": "https://thepihut.com/search?q=ReSpeaker%20XMOS%20XVF3800",
    "youtubePl": "Kora słucha przez czteromikrofonowy moduł ReSpeaker XVF3800 z redukcją echa i szumu.",
    "youtubeEn": "Kora listens through a four-microphone ReSpeaker XVF3800 array with echo and noise reduction."
  },
  {
    "id": "cam3",
    "name": "Raspberry Pi Camera Module 3",
    "short": "Kamera dzienna z autofokusem",
    "category": "Sensory",
    "supplier": "Pi Hut",
    "project": "Kora / VEGA",
    "status": "W drodze",
    "price": "£27.50",
    "accent": "cyan",
    "spec": "12 MP • autofocus • standardowe pole widzenia",
    "url": "https://thepihut.com/search?q=Raspberry%20Pi%20Camera%20Module%203%20Standard",
    "youtubePl": "Obraz dzienny zapewnia Raspberry Pi Camera Module 3 z autofokusem.",
    "youtubeEn": "Daytime vision is provided by a Raspberry Pi Camera Module 3 with autofocus."
  },
  {
    "id": "cam3-noir",
    "name": "Raspberry Pi Camera Module 3 Wide NoIR",
    "short": "Szerokokątna kamera nocna bez filtra IR",
    "category": "Sensory",
    "supplier": "Pi Hut",
    "project": "Kora / VEGA",
    "status": "Używam",
    "accent": "cyan",
    "spec": "Sony IMX708 • 12 MP • autofocus • szerokie pole widzenia • czułość na podczerwień",
    "url": "https://thepihut.com/search?q=Raspberry%20Pi%20Camera%20Module%203%20Wide%20NoIR",
    "youtubePl": "Obraz nocny Kory zapewnia szerokokątna kamera Raspberry Pi Camera Module 3 NoIR z sensorem IMX708.",
    "youtubeEn": "Kora's night vision uses a wide-angle Raspberry Pi Camera Module 3 NoIR with an IMX708 sensor."
  },
  {
    "id": "x1203",
    "name": "SupTronics X1203 V1.0 UPS",
    "short": "Awaryjne zasilanie Raspberry Pi 5",
    "category": "Zasilanie",
    "supplier": "Pi Hut",
    "project": "Kora / VEGA",
    "status": "Mam",
    "price": "£39.70",
    "accent": "amber",
    "spec": "5.1 V / 5 A • ogniwa 18650 poza płytką • montaż na pogo pinach",
    "url": "https://thepihut.com/search?q=SupTronics%20X1203%20UPS%20Raspberry%20Pi%205",
    "youtubePl": "Raspberry Pi 5 jest podtrzymywane przez UPS SupTronics X1203 o wydajności 5,1 V / 5 A.",
    "youtubeEn": "The Raspberry Pi 5 is backed by a SupTronics X1203 UPS rated at 5.1 V / 5 A."
  },
  {
    "id": "psu45",
    "name": "Raspberry Pi 45 W USB-C PSU",
    "short": "Oficjalny zasilacz UK",
    "category": "Zasilanie",
    "supplier": "Pi Hut",
    "project": "Kora / VEGA",
    "status": "W drodze",
    "price": "£17.90",
    "accent": "amber",
    "spec": "45 W • USB-C PD • wtyczka UK",
    "url": "https://thepihut.com/search?q=Raspberry%20Pi%2045W%20USB-C%20Power%20Supply%20UK",
    "youtubePl": "Do zasilania i testów Raspberry Pi używam oficjalnego zasilacza USB-C 45 W.",
    "youtubeEn": "I use the official 45 W USB-C power supply for Raspberry Pi power and bench testing."
  },
  {
    "id": "mpr121",
    "name": "Adafruit MPR121 — 12-Key Touch",
    "short": "Sterowanie dotykowe bez przycisków",
    "category": "Sensory",
    "supplier": "Pi Hut",
    "project": "Kora / VEGA",
    "status": "W drodze",
    "price": "£11.20",
    "accent": "cyan",
    "spec": "12 wejść pojemnościowych • I²C • STEMMA QT",
    "url": "https://thepihut.com/search?q=Adafruit%20MPR121%2012-Key%20Capacitive%20Touch",
    "youtubePl": "Dotyk wykrywa 12-kanałowy czujnik pojemnościowy Adafruit MPR121.",
    "youtubeEn": "Touch input is handled by a 12-channel Adafruit MPR121 capacitive sensor."
  },
  {
    "id": "portsplus",
    "name": "RasPiO Portsplus GPIO",
    "short": "Czytelna mapa pinów Raspberry Pi",
    "category": "Połączenia",
    "supplier": "Pi Hut",
    "project": "Warsztat",
    "status": "W drodze",
    "accent": "slate",
    "spec": "Nakładka opisowa GPIO • szybsze prototypowanie • mniej pomyłek",
    "url": "https://thepihut.com/search?q=RasPiO%20Portsplus%20GPIO%20Board",
    "youtubePl": "Do szybkiego prototypowania używam płytki RasPiO Portsplus z czytelnym opisem GPIO.",
    "youtubeEn": "For quick prototyping I use a RasPiO Portsplus board with clearly labelled GPIO pins."
  },
  {
    "id": "speaker-usb",
    "name": "Mini External USB Stereo Speaker",
    "short": "Kompaktowy głośnik do prototypów",
    "category": "Audio",
    "supplier": "Pi Hut",
    "project": "Kora / VEGA",
    "status": "W drodze",
    "price": "£14.40",
    "accent": "pink",
    "spec": "USB • stereo • mała obudowa",
    "url": "https://thepihut.com/search?q=Mini%20External%20USB%20Stereo%20Speaker",
    "youtubePl": "Dźwięk podczas testów zapewnia kompaktowy zewnętrzny głośnik stereo USB.",
    "youtubeEn": "A compact external USB stereo speaker provides audio during testing."
  },
  {
    "id": "camera-cable-300",
    "name": "Taśma kamery do Raspberry Pi 5 — 300 mm",
    "short": "Dłuższe połączenie kamery z komputerem",
    "category": "Połączenia",
    "supplier": "Pi Hut",
    "project": "Kora / VEGA",
    "status": "W drodze",
    "accent": "slate",
    "spec": "300 mm • złącze MIPI do Raspberry Pi 5 • elastyczna taśma",
    "url": "https://thepihut.com/search?q=Camera%20Adapter%20Cable%20Raspberry%20Pi%205%20300mm",
    "youtubePl": "Kamera jest połączona z Raspberry Pi 5 elastyczną taśmą MIPI o długości 300 mm.",
    "youtubeEn": "The camera is connected to the Raspberry Pi 5 with a 300 mm flexible MIPI cable."
  },
  {
    "id": "usb-c-molex",
    "name": "Przewód USB-C → Molex 4-pin",
    "short": "Zasilanie urządzeń z gniazda Molex",
    "category": "Połączenia",
    "supplier": "Pi Hut",
    "project": "Warsztat",
    "status": "W drodze",
    "accent": "slate",
    "spec": "USB-C • gniazdo Molex 4-pin • przewód zasilający",
    "url": "https://thepihut.com/search?q=USB-C%20to%204-Pin%20Molex%20Socket%20Cable",
    "youtubePl": "Do nietypowych połączeń zasilania używam przewodu USB-C z czteropinowym gniazdem Molex.",
    "youtubeEn": "For custom power connections I use a USB-C cable with a four-pin Molex socket."
  },
  {
    "id": "poe-header",
    "name": "PoE+ HAT Extra Tall Header Kit",
    "short": "Wyższe złącze GPIO pod nakładki",
    "category": "Połączenia",
    "supplier": "Pi Hut",
    "project": "Warsztat",
    "status": "W drodze",
    "accent": "slate",
    "spec": "Podwyższone GPIO • montaż wciskany • do PoE+ HAT",
    "url": "https://thepihut.com/search?q=PoE%2B%20HAT%20Push-Fit%20Extra%20Tall%20Header%20Kit",
    "youtubePl": "Wyższe złącze GPIO pozwala zachować dostęp do pinów podczas używania nakładki PoE+ HAT.",
    "youtubeEn": "An extra-tall GPIO header keeps the pins accessible while using a PoE+ HAT."
  },
  {
    "id": "pca9685",
    "name": "PCA9685 — 16 kanałów PWM",
    "short": "Sterownik serwomechanizmów",
    "category": "Sterowanie",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Używam",
    "price": "£4.99 / 2 szt.",
    "accent": "green",
    "spec": "16 kanałów • 12-bit PWM • magistrala I²C",
    "url": "https://www.aliexpress.com/item/1005010288617803.html",
    "youtubePl": "Ruchem serwomechanizmów sterują 16-kanałowe moduły PCA9685 przez magistralę I²C.",
    "youtubeEn": "The servos are controlled by 16-channel PCA9685 modules over I²C."
  },
  {
    "id": "servo-controller-32ch",
    "name": "USB — 32-kanałowy sterownik serw",
    "short": "Jedna płytka dla 18 serw nóg Kory",
    "category": "Sterowanie",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "green",
    "spec": "32 kanały PWM • sterowanie przez USB • osobne zasilanie serw",
    "url": "https://www.aliexpress.com/w/wholesale-32-channel-usb-servo-controller.html",
    "youtubePl": "Osiemnastoma serwami nóg Kory steruje jedna 32-kanałowa płytka podłączana przez USB.",
    "youtubeEn": "Kora's 18 leg servos are controlled by one 32-channel board connected over USB."
  },
  {
    "id": "esp32c6",
    "name": "ESP32-C6 SuperMini",
    "short": "Mały kontroler Wi-Fi i Bluetooth",
    "category": "Sterowanie",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Używam",
    "price": "£2.95 / szt.",
    "accent": "green",
    "spec": "Wi-Fi 6 • Bluetooth 5 • RISC-V • kompaktowy format",
    "url": "https://www.aliexpress.com/item/1005010177876942.html",
    "youtubePl": "Sterowanie niskopoziomowe realizuje kompaktowa płytka ESP32-C6 SuperMini.",
    "youtubeEn": "Low-level control is handled by a compact ESP32-C6 SuperMini board."
  },
  {
    "id": "esp32s3",
    "name": "ESP32-S3 N16R8",
    "short": "Kontroler z 16 MB Flash i 8 MB PSRAM",
    "category": "Sterowanie",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Mam",
    "price": "£3.99 / szt.",
    "accent": "green",
    "spec": "16 MB Flash • 8 MB PSRAM • Wi-Fi • Bluetooth",
    "url": "https://www.aliexpress.com/item/1005006418608267.html",
    "youtubePl": "W prototypach używam ESP32-S3 N16R8 z 16 MB Flash i 8 MB PSRAM.",
    "youtubeEn": "My prototypes use ESP32-S3 N16R8 boards with 16 MB Flash and 8 MB PSRAM."
  },
  {
    "id": "esp32c3",
    "name": "ESP32-C3 SuperMini",
    "short": "Maleńka płytka do szybkich prototypów",
    "category": "Sterowanie",
    "supplier": "AliExpress",
    "project": "Uniwersalne",
    "status": "Mam",
    "accent": "green",
    "spec": "RISC-V 160 MHz • Wi-Fi 2,4 GHz • Bluetooth 5 LE • USB-C • 4 MB Flash",
    "url": "https://www.aliexpress.com/w/wholesale-esp32-c3-supermini.html",
    "youtubePl": "Do małych układów sterujących używam kompaktowej płytki ESP32-C3 SuperMini z Wi-Fi i Bluetooth LE.",
    "youtubeEn": "For small control systems I use the compact ESP32-C3 SuperMini board with Wi-Fi and Bluetooth LE."
  },
  {
    "id": "huskylens",
    "name": "DFRobot HUSKYLENS — SEN0305",
    "short": "Wizja i rozpoznawanie obiektów w starszej Korze",
    "category": "Sensory",
    "supplier": "DFRobot",
    "project": "Kora / VEGA",
    "status": "Używam",
    "accent": "cyan",
    "spec": "Kendryte K210 • ekran IPS 2″ • twarze, obiekty, kolory, linie i kody • I²C / UART",
    "url": "https://www.dfrobot.com/product-1922.html",
    "youtubePl": "W jednej ze starszych wersji Kory moduł DFRobot HUSKYLENS rozpoznawał twarze, obiekty, kolory i linie.",
    "youtubeEn": "In one of Kora's earlier versions, the DFRobot HUSKYLENS module recognised faces, objects, colours and lines."
  },
  {
    "id": "dfrobot-voice",
    "name": "DFRobot DF2301Q — SEN0539",
    "short": "Rozpoznawanie poleceń głosowych bez internetu",
    "category": "Audio",
    "supplier": "DFRobot",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "pink",
    "spec": "121 poleceń wbudowanych • 17 własnych • I²C / UART • mikrofony i komunikaty głosowe",
    "url": "https://wiki.dfrobot.com/sen0539-en/",
    "youtubePl": "Polecenia głosowe może rozpoznawać lokalnie moduł DFRobot DF2301Q, bez połączenia z internetem.",
    "youtubeEn": "Voice commands can be recognised locally by the DFRobot DF2301Q module without an internet connection."
  },
  {
    "id": "rplidar-c1",
    "name": "SLAMTEC RPLIDAR C1",
    "short": "Kompaktowy lidar posiadany do testów",
    "category": "Sensory",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "cyan",
    "spec": "360° • pomiar ToF • zasięg do 12 m • osobny od RPLIDAR A2 używanego obecnie w Korze",
    "url": "https://www.aliexpress.com/item/1005006190309082.html",
    "youtubePl": "Do testów mam również kompaktowy lidar SLAMTEC RPLIDAR C1; obecna Kora korzysta z modelu RPLIDAR A2.",
    "youtubeEn": "I also own a compact SLAMTEC RPLIDAR C1 for testing; the current Kora system uses an RPLIDAR A2."
  },
  {
    "id": "vl53l1x",
    "name": "VL53L1X Time-of-Flight",
    "short": "Laserowy pomiar odległości",
    "category": "Sensory",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Używam",
    "accent": "cyan",
    "spec": "ToF • I²C • zasięg do 4 m",
    "url": "https://www.aliexpress.com/item/1005006459241792.html",
    "youtubePl": "Odległość z przodu mierzy laserowy czujnik Time-of-Flight VL53L1X o zasięgu do 4 metrów.",
    "youtubeEn": "Front distance is measured by a VL53L1X Time-of-Flight sensor with a range of up to 4 metres."
  },
  {
    "id": "bmi160",
    "name": "BMI160 — IMU 6DoF",
    "short": "Akcelerometr i żyroskop",
    "category": "Sensory",
    "supplier": "AliExpress",
    "project": "Roboty mobilne",
    "status": "Mam",
    "price": "£1.00 / szt.",
    "accent": "cyan",
    "spec": "6 osi • akcelerometr • żyroskop • I²C / SPI",
    "url": "https://www.aliexpress.com/item/1005006351402967.html",
    "youtubePl": "Ruch i przechylenie mierzy sześcioosiowy moduł BMI160 z akcelerometrem i żyroskopem.",
    "youtubeEn": "Motion and tilt are measured by a six-axis BMI160 module with an accelerometer and gyroscope."
  },
  {
    "id": "apds9960",
    "name": "APDS-9960",
    "short": "Gesty, zbliżenie, kolor i światło",
    "category": "Sensory",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Mam",
    "price": "£2.00 / szt.",
    "accent": "cyan",
    "spec": "Gesty • zbliżenie • RGB • natężenie światła • I²C",
    "url": "https://www.aliexpress.com/item/1005008637735476.html",
    "youtubePl": "Gesty, zbliżenie i kolor światła wykrywa wielofunkcyjny czujnik APDS-9960.",
    "youtubeEn": "Gestures, proximity and light colour are detected by an APDS-9960 multifunction sensor."
  },
  {
    "id": "ld2410c",
    "name": "LD2410C — radar 24 GHz",
    "short": "Wykrywanie obecności człowieka",
    "category": "Sensory",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "cyan",
    "spec": "FMCW 24 GHz • wykrywa ruch i mikroruchy • UART / Bluetooth",
    "url": "https://www.aliexpress.com/item/1005007035360905.html",
    "youtubePl": "Obecność człowieka wykrywa radar FMCW LD2410C pracujący w paśmie 24 GHz.",
    "youtubeEn": "Human presence is detected by an LD2410C FMCW radar operating at 24 GHz."
  },
  {
    "id": "bts7960",
    "name": "BTS7960 — mostek H 43 A",
    "short": "Sterownik silników dużej mocy",
    "category": "Napędy",
    "supplier": "AliExpress",
    "project": "Roboty mobilne",
    "status": "Mam",
    "price": "£8.19 / 2 szt.",
    "accent": "red",
    "spec": "Mostek H • do 43 A deklarowane przez sprzedawcę • PWM",
    "url": "https://www.aliexpress.com/item/1005006264172513.html",
    "youtubePl": "Silnikami dużej mocy sterują moduły mostka H BTS7960.",
    "youtubeEn": "High-power motors are controlled by BTS7960 H-bridge modules."
  },
  {
    "id": "rds5180",
    "name": "RDS5180 — serwo 80 kg",
    "short": "Mocne serwo dwuosiowe",
    "category": "Napędy",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "red",
    "spec": "7.4 V • metalowe przekładnie • podwójny wał",
    "url": "https://www.aliexpress.com/item/1005010064568049.html",
    "youtubePl": "Do ruchów wymagających dużego momentu wykorzystuję dwuosiowe serwo RDS5180 z metalową przekładnią.",
    "youtubeEn": "For high-torque movement I use an RDS5180 dual-shaft servo with metal gears."
  },
  {
    "id": "rds3115",
    "name": "RDS3115MG — serwo 17 kg",
    "short": "Serwo z wcześniejszej czteronożnej Kory",
    "category": "Napędy",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "red",
    "spec": "180° / 270° • metalowe przekładnie • podwójny wał",
    "url": "https://www.aliexpress.com/item/1005005471524950.html",
    "youtubePl": "We wcześniejszej czteronożnej wersji Kory używałem dwuosiowych serw RDS3115MG z metalowymi przekładniami.",
    "youtubeEn": "An earlier four-legged version of Kora used RDS3115MG dual-shaft servos with metal gears."
  },
  {
    "id": "sg90",
    "name": "SG90 — mikroserwo 9 g",
    "short": "Małe i lekkie serwo 180°",
    "category": "Napędy",
    "supplier": "AliExpress",
    "project": "Uniwersalne",
    "status": "Mam",
    "price": "£7.99 / 10 szt.",
    "accent": "red",
    "spec": "9 g • 180° • PWM • lekkie mechanizmy",
    "url": "https://www.aliexpress.com/item/1005007173214082.html",
    "youtubePl": "Lekkie mechanizmy poruszają popularne mikroserwa SG90 o masie 9 gramów.",
    "youtubeEn": "Lightweight mechanisms are moved by popular 9-gram SG90 micro servos."
  },
  {
    "id": "dc5v15a",
    "name": "Przetwornica DC-DC 5 V / 15 A",
    "short": "Zasilanie elektroniki z 12–24 V",
    "category": "Zasilanie",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Mam",
    "price": "£5.69 / szt.",
    "accent": "amber",
    "spec": "Wejście 12–24 V • wyjście 5 V • deklarowane 15 A",
    "url": "https://www.aliexpress.com/item/1005007062967909.html",
    "youtubePl": "Napięcie instalacji 12–24 V obniża przetwornica DC-DC do 5 V dla elektroniki sterującej.",
    "youtubeEn": "A DC-DC converter steps the 12–24 V supply down to 5 V for the control electronics."
  },
  {
    "id": "dc-stepdown-10a",
    "name": "Przetwornica DC-DC 11,1 V → 5 V / 10 A",
    "short": "Osobny tor 5 V dla komputera i elektroniki",
    "category": "Zasilanie",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "amber",
    "spec": "Wejście z pakietu 3S 11,1 V • wyjście 5 V • deklarowane 10 A • nie zasila szyny serw 6 V",
    "url": "https://www.aliexpress.com/w/wholesale-12v-to-5v-10a-dc-converter.html",
    "youtubePl": "Elektronika Kory ma osobny tor 5 V zasilany z pakietu 11,1 V przez przetwornicę DC-DC 10 A; serwa korzystają z oddzielnej szyny około 6 V.",
    "youtubeEn": "Kora's electronics use a separate 5 V rail supplied from the 11.1 V pack through a 10 A DC-DC converter; the servos use a separate rail at about 6 V."
  },
  {
    "id": "dcwide",
    "name": "Przetwornica DC-DC 12–90 V → 5 V",
    "short": "Szeroki zakres napięcia wejściowego",
    "category": "Zasilanie",
    "supplier": "AliExpress",
    "project": "Roboty mobilne",
    "status": "Mam",
    "price": "£5.79",
    "accent": "amber",
    "spec": "Wejście 12–90 V • wyjście 5 V • deklarowane 10 A",
    "url": "https://www.aliexpress.com/item/1005008118059523.html",
    "youtubePl": "Elektronikę zasilam przez szerokozakresową przetwornicę DC-DC 12–90 V na 5 V.",
    "youtubeEn": "The electronics are powered through a wide-input 12–90 V to 5 V DC-DC converter."
  },
  {
    "id": "ws2812matrix",
    "name": "Matryca WS2812B 16×16",
    "short": "256 adresowalnych diod RGB",
    "category": "Światło",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Używam",
    "price": "£5.40 / szt.",
    "accent": "blue",
    "spec": "256 pikseli • RGB • 5 V • indywidualne sterowanie",
    "url": "https://www.aliexpress.com/item/1005008565110209.html",
    "youtubePl": "Animacje twarzy wyświetla matryca 16×16 z 256 indywidualnie sterowanymi diodami WS2812B.",
    "youtubeEn": "Face animations are displayed on a 16×16 matrix with 256 individually addressable WS2812B LEDs."
  },
  {
    "id": "led-ring16",
    "name": "Pierścień LED RGB — 16 diod",
    "short": "Sygnalizacja stanu i animacje świetlne Kory",
    "category": "Światło",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "blue",
    "spec": "16 adresowalnych diod RGB • zasilanie 5 V • sterowanie szeregowe",
    "url": "https://www.aliexpress.com/w/wholesale-16-led-rgb-ring.html",
    "youtubePl": "Stan i reakcje Kory może sygnalizować pierścień z 16 adresowalnymi diodami RGB.",
    "youtubeEn": "Kora's state and reactions can be indicated by a ring of 16 individually addressable RGB LEDs."
  },
  {
    "id": "rgb-strip",
    "name": "Pasek LED RGB",
    "short": "Kolorowe oświetlenie projektów i radia",
    "category": "Światło",
    "supplier": "AliExpress",
    "project": "Audio",
    "status": "Używam",
    "accent": "blue",
    "spec": "Diody RGB • kanały R/G/B • elastyczna taśma • efekty świetlne",
    "url": "https://www.aliexpress.com/w/wholesale-rgb-led-strip.html",
    "youtubePl": "Efekty świetlne radia realizuje elastyczny pasek LED RGB sterowany z układu elektronicznego.",
    "youtubeEn": "The radio's lighting effects are produced by a flexible RGB LED strip controlled by the electronics."
  },
  {
    "id": "pcm5102",
    "name": "PCM5102A — przetwornik I²S DAC",
    "short": "Cyfrowe audio dla Raspberry Pi i ESP32",
    "category": "Audio",
    "supplier": "AliExpress",
    "project": "Audio",
    "status": "Używam",
    "price": "£1.60",
    "accent": "pink",
    "spec": "I²S • wyjście stereo analog • 32-bit DAC",
    "url": "https://www.aliexpress.com/item/1005006953485069.html",
    "youtubePl": "Cyfrowy dźwięk I²S zamienia na sygnał analogowy moduł DAC PCM5102A.",
    "youtubeEn": "A PCM5102A DAC converts the digital I²S audio stream into an analogue stereo signal."
  },
  {
    "id": "inmp441",
    "name": "INMP441 — mikrofon I²S",
    "short": "Cyfrowy mikrofon MEMS",
    "category": "Audio",
    "supplier": "AliExpress",
    "project": "Audio",
    "status": "Mam",
    "price": "£2.09 / szt.",
    "accent": "pink",
    "spec": "MEMS • I²S • do ESP32 • niski pobór mocy",
    "url": "https://www.aliexpress.com/item/1005008869908588.html",
    "youtubePl": "Dźwięk rejestruje cyfrowy mikrofon MEMS INMP441 po magistrali I²S.",
    "youtubeEn": "Audio is captured by an INMP441 digital MEMS microphone over I²S."
  },
  {
    "id": "ili9341",
    "name": "Wyświetlacz TFT 2.8″ ILI9341",
    "short": "Kolorowy ekran dotykowy SPI",
    "category": "Wyświetlacze",
    "supplier": "AliExpress",
    "project": "Uniwersalne",
    "status": "Mam",
    "price": "£4.69 / szt.",
    "accent": "blue",
    "spec": "240×320 px • SPI • panel dotykowy",
    "url": "https://www.aliexpress.com/item/1005006425985706.html",
    "youtubePl": "Interfejs wyświetlam na kolorowym ekranie dotykowym TFT 2,8 cala z kontrolerem ILI9341.",
    "youtubeEn": "The interface is shown on a 2.8-inch colour TFT touchscreen driven by the ILI9341 controller."
  },
  {
    "id": "oled12864",
    "name": "OLED 0.96″ 128×64 — SSD1306",
    "short": "Mały wyświetlacz, który uwielbiam",
    "category": "Wyświetlacze",
    "supplier": "AliExpress",
    "project": "Kora / VEGA",
    "status": "Używam",
    "accent": "blue",
    "spec": "128×64 px • OLED • I²C • kontroler SSD1306 • 3,3–5 V",
    "url": "https://www.aliexpress.com/w/wholesale-oled-128x64-ssd1306.html",
    "youtubePl": "Informacje i proste animacje pokazuję na moim ulubionym małym wyświetlaczu OLED 128×64 z kontrolerem SSD1306.",
    "youtubeEn": "I display information and simple animations on my favourite small 128×64 OLED screen driven by the SSD1306 controller."
  },
  {
    "id": "ir-sensor",
    "name": "Czujnik podczerwieni IR",
    "short": "Bezdotykowe wykrywanie dłoni i przeszkód",
    "category": "Sensory",
    "supplier": "AliExpress",
    "project": "Audio",
    "status": "Używam",
    "accent": "cyan",
    "spec": "Nadajnik i odbiornik IR • regulowana czułość • wyjście cyfrowe",
    "url": "https://www.aliexpress.com/w/wholesale-infrared-obstacle-sensor-module.html",
    "youtubePl": "Radiem steruję bezdotykowo za pomocą czujników podczerwieni wykrywających ruch dłoni.",
    "youtubeEn": "I control the radio without touching it by using infrared sensors that detect hand movement."
  },
  {
    "id": "dupont",
    "name": "Przewody Dupont 10–30 cm",
    "short": "Komplet męski–męski, męski–żeński i żeński–żeński",
    "category": "Połączenia",
    "supplier": "AliExpress",
    "project": "Warsztat",
    "status": "Mam",
    "accent": "slate",
    "spec": "40 żył • 10 / 20 / 30 cm • MM + MF + FF",
    "url": "https://www.aliexpress.com/item/1005003641187997.html",
    "youtubePl": "Połączenia prototypowe wykonuję kompletami przewodów Dupont: męski–męski, męski–żeński i żeński–żeński.",
    "youtubeEn": "Prototype connections are made with male-to-male, male-to-female and female-to-female Dupont jumper wire sets."
  },
  {
    "id": "powerbank-18650",
    "name": "Obudowy powerbank 1–4× 18650",
    "short": "Modułowe obudowy do ogniw 18650",
    "category": "Zasilanie",
    "supplier": "AliExpress",
    "project": "Warsztat",
    "status": "Mam",
    "accent": "amber",
    "spec": "Warianty 1 / 2 / 3 / 4 ogniwa • obudowa z elektroniką USB • ogniwa osobno",
    "url": "https://www.aliexpress.com/w/wholesale-18650-power-bank-case.html",
    "youtubePl": "Do przenośnego zasilania prototypów używam obudów powerbank mieszczących od jednego do czterech ogniw 18650.",
    "youtubeEn": "For portable prototype power I use power-bank enclosures holding between one and four 18650 cells."
  },
  {
    "id": "xh254",
    "name": "Złącza JST-XH 2.54 mm",
    "short": "Przewody i gniazda czteropinowe",
    "category": "Połączenia",
    "supplier": "AliExpress",
    "project": "Warsztat",
    "status": "Mam",
    "price": "£1.14 / 5 kpl.",
    "accent": "slate",
    "spec": "Raster 2.54 mm • 4 piny • przewody 10 cm",
    "url": "https://www.aliexpress.com/item/1005007460897865.html",
    "youtubePl": "Moduły łączę rozłącznymi złączami JST-XH 2,54 mm.",
    "youtubeEn": "Modules are connected with detachable 2.54 mm JST-XH connectors."
  },
  {
    "id": "cnc-hrc68",
    "name": "Frez węglikowy HRC68 — 4 ostrza",
    "short": "Frez do precyzyjnej obróbki metalu",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£3.02",
    "accent": "green",
    "spec": "1,5 mm • chwyt 4 mm • długość 50 mm • 4 ostrza",
    "url": "https://www.aliexpress.com/item/1005004697788231.html",
    "youtubePl": "Do precyzyjnej obróbki używam czteroostrzowego frezu węglikowego HRC68 o średnicy 1,5 mm.",
    "youtubeEn": "For precision machining I use a 1.5 mm HRC68 four-flute carbide end mill."
  },
  {
    "id": "cnc-grbl2",
    "name": "Sterownik GRBL 32-bit — 2 osie",
    "short": "Płyta sterująca grawerką laserową",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£14.80",
    "accent": "green",
    "spec": "32-bit MCU • USB-C • 2 osie • sterowniki zintegrowane",
    "url": "https://www.aliexpress.com/item/1005004183745208.html",
    "youtubePl": "Dwoma osiami grawerki steruje 32-bitowa płyta GRBL z portem USB-C.",
    "youtubeEn": "A 32-bit GRBL board with USB-C controls the engraver's two axes."
  },
  {
    "id": "cnc-rotary",
    "name": "Moduł obrotowy TwoTrees",
    "short": "Grawerowanie przedmiotów cylindrycznych",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£30.95",
    "accent": "red",
    "spec": "Napęd rolkowy • oś obrotowa • puszki i elementy cylindryczne",
    "url": "https://www.aliexpress.com/item/1005002810671779.html",
    "youtubePl": "Moduł obrotowy TwoTrees pozwala grawerować puszki i inne cylindryczne przedmioty.",
    "youtubeEn": "The TwoTrees rotary module enables engraving on cans and other cylindrical objects."
  },
  {
    "id": "cnc-z-axis",
    "name": "Moduł osi Z 2040V",
    "short": "Regulacja wysokości głowicy laserowej",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£15.47",
    "accent": "red",
    "spec": "Profil 2040V • regulacja osi Z • uchwyt głowicy",
    "url": "https://www.aliexpress.com/item/4000863582142.html",
    "youtubePl": "Moduł osi Z umożliwia precyzyjne ustawienie wysokości głowicy względem materiału.",
    "youtubeEn": "The Z-axis module provides precise adjustment of the head height above the workpiece."
  },
  {
    "id": "cnc-psu24",
    "name": "Zasilacz na szynę DIN — 24 V / 2,5 A",
    "short": "Zasilanie sterowania i napędów",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£6.14",
    "accent": "amber",
    "spec": "60 W • 24 V DC • 2,5 A • montaż na szynie DIN",
    "url": "https://www.aliexpress.com/item/1005004654602581.html",
    "youtubePl": "Sterowanie maszyny zasila kompaktowy zasilacz 24 V / 2,5 A montowany na szynie DIN.",
    "youtubeEn": "The machine control system is powered by a compact 24 V / 2.5 A DIN-rail power supply."
  },
  {
    "id": "cnc-endmill-2f",
    "name": "Frez DREANIQUE 2 mm — 2 ostrza",
    "short": "Frez prosty do drewna, MDF i tworzyw",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Używam",
    "price": "£1.65 / szt.",
    "accent": "green",
    "spec": "2 mm • długość robocza 17 / 22 mm • węglik spiekany",
    "url": "https://www.aliexpress.com/item/1005001580397962.html",
    "youtubePl": "Do wycinania i grawerowania używam dwuostrzowych frezów DREANIQUE o średnicy 2 mm.",
    "youtubeEn": "For cutting and engraving I use 2 mm DREANIQUE two-flute carbide end mills."
  },
  {
    "id": "cnc-dust-shoe",
    "name": "Szczotka odciągu wrzeciona — 65 mm",
    "short": "Zbieranie pyłu bezpośrednio przy frezie",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Używam",
    "price": "£12.78",
    "accent": "slate",
    "spec": "Mocowanie 65 mm • szczotka ochronna • króciec odciągu",
    "url": "https://www.aliexpress.com/item/1005004235237465.html",
    "youtubePl": "Szczotka odciągu o średnicy 65 mm zbiera pył bezpośrednio wokół wrzeciona.",
    "youtubeEn": "A 65 mm spindle dust shoe collects debris directly around the cutter."
  },
  {
    "id": "cnc-controller4",
    "name": "Sterownik CNC GRBL — 4 osie",
    "short": "Główna płyta sterowania XYZA",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Używam",
    "price": "£51.76",
    "accent": "violet",
    "spec": "32-bit MCU • osie X/Y/Z/A • 4× DRV8825 • sterowanie wrzecionem do 500 W",
    "url": "https://www.aliexpress.com/item/1005003918795013.html",
    "youtubePl": "Ruchem osi X, Y, Z i A steruje 32-bitowa płyta GRBL z czterema sterownikami DRV8825.",
    "youtubeEn": "A 32-bit GRBL board with four DRV8825 drivers controls the X, Y, Z and A axes."
  },
  {
    "id": "cnc-nema17",
    "name": "NEMA17 — 60 mm / 71 Ncm",
    "short": "Silnik krokowy do osi CNC",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Używam",
    "accent": "red",
    "spec": "2 fazy • 1,8° • 1,8 A • 0,71 Nm / 71 Ncm • korpus 60 mm • przewód 4-żyłowy",
    "url": "https://www.aliexpress.com/item/4000934544704.html",
    "youtubePl": "Osie maszyny napędzają silniki krokowe NEMA17 o momencie 71 Ncm i prądzie 1,8 A na fazę.",
    "youtubeEn": "The machine axes are driven by NEMA17 stepper motors rated at 71 Ncm and 1.8 A per phase."
  },
  {
    "id": "cnc-sbr",
    "name": "Prowadnice liniowe SBR + wózki UU/LUU",
    "short": "Sztywne prowadzenie osi frezarki",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Używam",
    "accent": "slate",
    "spec": "SBR10 / 12 / 16 / 20 • wózki SBRxxUU i SBRxxLUU • podparte wałki liniowe",
    "url": "https://www.aliexpress.com/w/wholesale-sbr-linear-rail-sbr16uu.html",
    "youtubePl": "Ruch osi frezarki prowadzą podparte prowadnice liniowe SBR z wózkami kulkowymi UU i LUU.",
    "youtubeEn": "The router axes run on supported SBR linear rails with UU and LUU ball-bearing blocks."
  },
  {
    "id": "cnc-spindle-vfd",
    "name": "Wrzeciono 800 W + VFD 1,5 kW",
    "short": "Główny napęd frezarki z regulacją obrotów",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Używam",
    "price": "£157.12",
    "accent": "violet",
    "spec": "Zestaw 220 V • wrzeciono 800 W • falownik 1,5 kW • uchwyt ER11",
    "url": "https://www.aliexpress.com/item/1005003013020654.html",
    "youtubePl": "Frezarkę napędza wrzeciono 800 W sterowane falownikiem VFD 1,5 kW, który pozwala regulować prędkość obrotową.",
    "youtubeEn": "The router uses an 800 W spindle controlled by a 1.5 kW VFD for adjustable spindle speed."
  },
  {
    "id": "cnc-pump",
    "name": "Pompa chłodzenia wrzeciona — 80 W",
    "short": "Obieg wody dla chłodzonego wrzeciona",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Używam",
    "accent": "cyan",
    "spec": "80 W • wysokość podnoszenia 3,5 m • chłodzenie wodne wrzecion 1,5 / 2,2 kW",
    "url": "https://www.aliexpress.com/w/wholesale-80w-3.5m-cnc-water-pump.html",
    "youtubePl": "Temperaturę wrzeciona utrzymuje obieg chłodzenia wodnego z pompą 80 W o wysokości podnoszenia 3,5 metra.",
    "youtubeEn": "Spindle temperature is controlled by a water-cooling loop with an 80 W pump rated for a 3.5-metre head."
  },
  {
    "id": "cnc-bits",
    "name": "Frezy grawerskie 0,8 / 3,175 mm — 10 szt.",
    "short": "Tytanowane frezy do grawerowania i PCB",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£4.39",
    "accent": "green",
    "spec": "10 sztuk • ostrze 0,8 mm • chwyt 3,175 mm • węglik z powłoką tytanową",
    "url": "https://www.aliexpress.com/item/32867249964.html",
    "youtubePl": "Do drobnego grawerowania i obróbki PCB używam tytanowanych frezów węglikowych z chwytem 3,175 mm.",
    "youtubeEn": "For fine engraving and PCB machining I use titanium-coated carbide cutters with a 3.175 mm shank."
  },
  {
    "id": "cnc-stc1000",
    "name": "Regulator temperatury STC-1000",
    "short": "Sterowanie grzaniem albo chłodzeniem",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Mam",
    "accent": "amber",
    "spec": "Czujnik temperatury • wyświetlacz LED • wyjścia grzanie / chłodzenie • przekaźniki 10 A",
    "url": "https://www.aliexpress.com/w/wholesale-stc-1000-temperature-controller.html",
    "youtubePl": "Temperaturę układu kontroluje regulator STC-1000 z osobnymi wyjściami dla grzania i chłodzenia.",
    "youtubeEn": "System temperature is controlled by an STC-1000 regulator with separate heating and cooling outputs."
  },
  {
    "id": "cnc-c3018-upgrade",
    "name": "Zestaw prowadzenia CNC 3018 — SCV12VUU / T8",
    "short": "Łożyska i śruba do modernizacji osi",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Mam",
    "accent": "slate",
    "spec": "Łożyska SCV12VUU • wałki 10 / 12 mm • śruba pociągowa T8 • skok 4 mm",
    "url": "https://www.aliexpress.com/item/1005003292615018.html",
    "youtubePl": "Modernizację osi CNC 3018 wykonałem z użyciem łożysk liniowych SCV12VUU i śruby pociągowej T8.",
    "youtubeEn": "I upgraded the CNC 3018 axis using SCV12VUU linear bearings and a T8 lead screw."
  },
  {
    "id": "cnc-mks-dlc32",
    "name": "MKS DLC32 V2.1 + TS24-R",
    "short": "Sterownik GRBL offline z małym ekranem",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Mam",
    "accent": "violet",
    "spec": "ESP32 • GRBL • Wi-Fi • karta microSD • ekran TS24-R • sterowanie offline",
    "url": "https://www.aliexpress.com/w/wholesale-mks-dlc32-v2.1-ts24-r.html",
    "youtubePl": "Sterownik MKS DLC32 V2.1 z ekranem TS24-R pozwala obsługiwać maszynę i uruchamiać pliki bez komputera.",
    "youtubeEn": "The MKS DLC32 V2.1 controller with a TS24-R display can operate the machine and run files without a computer."
  },
  {
    "id": "cnc-spindle-clamp",
    "name": "Aluminiowy uchwyt wrzeciona 52 / 65 / 80 mm",
    "short": "Sztywne mocowanie silnika na osi Z",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Mam",
    "accent": "slate",
    "spec": "Aluminium • średnice 52 / 65 / 80 mm • dzielony zacisk • cztery śruby",
    "url": "https://www.aliexpress.com/w/wholesale-cnc-spindle-clamp-52mm-65mm-80mm.html",
    "youtubePl": "Wrzeciono jest zamocowane na osi Z w sztywnym, aluminiowym uchwycie zaciskowym.",
    "youtubeEn": "The spindle is secured to the Z axis with a rigid aluminium clamp mount."
  },
  {
    "id": "cnc-z-axis52",
    "name": "Aluminiowy moduł osi Z CNC 3018 — 52 mm",
    "short": "Kompletna oś z prowadnicami i śrubą",
    "category": "CNC",
    "supplier": "AliExpress",
    "project": "Frezarka CNC",
    "status": "Mam",
    "accent": "red",
    "spec": "Mocowanie wrzeciona 52 mm • silnik NEMA17 • prowadnice liniowe • aluminiowy stół przesuwny",
    "url": "https://www.aliexpress.com/item/1005001608926489.html",
    "youtubePl": "Moduł osi Z CNC 3018 łączy silnik NEMA17, prowadnice liniowe i aluminiowe mocowanie wrzeciona 52 mm.",
    "youtubeEn": "The CNC 3018 Z-axis module combines a NEMA17 motor, linear guides and a 52 mm aluminium spindle mount."
  }
];
