window.PARTS_CATALOG = [
  {
    "id": "rpi5-16",
    "name": "Raspberry Pi 5 — 16 GB",
    "short": "Główny komputer Kory",
    "category": "Komputery",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "violet",
    "spec": "16 GB RAM • czterordzeniowy CPU • PCIe • 2× MIPI",
    "url": "https://amzn.to/4imKH38",
    "youtubePl": "Głównym komputerem robota Kora jest Raspberry Pi 5 z 16 GB pamięci RAM.",
    "youtubeEn": "Kora's main computer is a Raspberry Pi 5 with 16 GB of RAM."
  },
  {
    "id": "ai-hat-2",
    "name": "Raspberry Pi AI HAT+ 2 — Hailo",
    "short": "Akcelerator Hailo do lokalnego przetwarzania modeli",
    "category": "Komputery",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Używam",
    "price": "£130.20*",
    "accent": "violet",
    "spec": "Akcelerator Hailo do obliczeń lokalnych • zestaw z taśmą MIPI 300 mm",
    "url": "https://www.amazon.co.uk/s?k=Raspberry%20Pi%20AI%20HAT%2B%202%20%E2%80%94%20Hailo%20Akcelerator%20Hailo%20do%20oblicze%C5%84%20lokalnych%20&tag=marcinkorapro-21",
    "youtubePl": "Do lokalnego przetwarzania wykorzystuję Raspberry Pi AI HAT+ 2 z akceleratorem Hailo.",
    "youtubeEn": "I use the Raspberry Pi AI HAT+ 2 with a Hailo accelerator for local model processing."
  },
  {
    "id": "xvf3800",
    "name": "ReSpeaker XVF3800 4-Mic Array",
    "short": "Cztery mikrofony i kierunkowe audio",
    "category": "Audio",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Używam",
    "price": "£51.50",
    "accent": "pink",
    "spec": "4 mikrofony • XMOS XVF3800 • redukcja echa i szumu",
    "url": "https://www.amazon.co.uk/s?k=ReSpeaker%20XVF3800%204-Mic%20Array%204%20mikrofony%20&tag=marcinkorapro-21",
    "youtubePl": "Kora słucha przez czteromikrofonowy moduł ReSpeaker XVF3800 z redukcją echa i szumu.",
    "youtubeEn": "Kora listens through a four-microphone ReSpeaker XVF3800 array with echo and noise reduction."
  },
  {
    "id": "cam3",
    "name": "Raspberry Pi Camera Module 3",
    "short": "Kamera dzienna z autofokusem",
    "category": "Sensory",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "price": "£27.50",
    "accent": "cyan",
    "spec": "12 MP • autofocus • standardowe pole widzenia",
    "url": "https://www.amazon.co.uk/s?k=Raspberry%20Pi%20Camera%20Module%203%2012%20MP%20&tag=marcinkorapro-21",
    "youtubePl": "Obraz dzienny zapewnia Raspberry Pi Camera Module 3 z autofokusem.",
    "youtubeEn": "Daytime vision is provided by a Raspberry Pi Camera Module 3 with autofocus."
  },
  {
    "id": "cam3-noir",
    "name": "Raspberry Pi Camera Module 3 Wide NoIR",
    "short": "Szerokokątna kamera nocna bez filtra IR",
    "category": "Sensory",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Używam",
    "accent": "cyan",
    "spec": "Sony IMX708 • 12 MP • autofocus • szerokie pole widzenia • czułość na podczerwień",
    "url": "https://www.amazon.co.uk/s?k=Raspberry%20Pi%20Camera%20Module%203%20Wide%20NoIR%20Sony%20IMX708%20&tag=marcinkorapro-21",
    "youtubePl": "Obraz nocny Kory zapewnia szerokokątna kamera Raspberry Pi Camera Module 3 NoIR z sensorem IMX708.",
    "youtubeEn": "Kora's night vision uses a wide-angle Raspberry Pi Camera Module 3 NoIR with an IMX708 sensor."
  },
  {
    "id": "x1203",
    "name": "SupTronics X1203 V1.0 UPS",
    "short": "UPS Raspberry Pi 5 — pełny stack wymaga dodatkowej mechaniki",
    "category": "Zasilanie",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Używam",
    "price": "£39.70",
    "accent": "amber",
    "spec": "5.1 V / 5 A • ogniwa 18650 poza płytką • pogo piny • Pi 5 + Hailo: dodatkowe dystanse M2.5 i wysoki header GPIO 2×20",
    "url": "https://www.amazon.co.uk/s?k=SupTronics%20X1203%20V1.0%20UPS%205.1%20V%20%2F%205%20A%20&tag=marcinkorapro-21",
    "youtubePl": "UPS SupTronics X1203 pasuje do Raspberry Pi 5, ale pełny stack z Hailo AI HAT+ wymaga dodatkowych dystansów M2.5 oraz wysokiego złącza GPIO 2×20 — standardowy zestaw nie zapewnia potrzebnego prześwitu.",
    "youtubeEn": "The SupTronics X1203 fits the Raspberry Pi 5, but the full stack with the Hailo AI HAT+ needs extra M2.5 standoffs and a 2×20 extra-tall GPIO header — the standard hardware does not provide enough clearance."
  },
  {
    "id": "psu45",
    "name": "Raspberry Pi 45 W USB-C PSU",
    "short": "Oficjalny zasilacz UK",
    "category": "Zasilanie",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "price": "£17.90",
    "accent": "amber",
    "spec": "45 W • USB-C PD • wtyczka UK",
    "url": "https://www.amazon.co.uk/s?k=Raspberry%20Pi%2045%20W%20USB-C%20PSU%2045%20W%20&tag=marcinkorapro-21",
    "youtubePl": "Do zasilania i testów Raspberry Pi używam oficjalnego zasilacza USB-C 45 W.",
    "youtubeEn": "I use the official 45 W USB-C power supply for Raspberry Pi power and bench testing."
  },
  {
    "id": "mpr121",
    "name": "Adafruit MPR121 — 12-Key Touch",
    "short": "Sterowanie dotykowe bez przycisków",
    "category": "Sensory",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "price": "£11.20",
    "accent": "cyan",
    "spec": "12 wejść pojemnościowych • I²C • STEMMA QT",
    "url": "https://www.amazon.co.uk/s?k=Adafruit%20MPR121%20%E2%80%94%2012-Key%20Touch%2012%20wej%C5%9B%C4%87%20pojemno%C5%9Bciowych%20&tag=marcinkorapro-21",
    "youtubePl": "Dotyk wykrywa 12-kanałowy czujnik pojemnościowy Adafruit MPR121.",
    "youtubeEn": "Touch input is handled by a 12-channel Adafruit MPR121 capacitive sensor."
  },
  {
    "id": "portsplus",
    "name": "RasPiO Portsplus GPIO",
    "short": "Czytelna mapa pinów Raspberry Pi",
    "category": "Połączenia",
    "supplier": "Amazon",
    "project": "Warsztat",
    "status": "Mam",
    "accent": "slate",
    "spec": "Nakładka opisowa GPIO • szybsze prototypowanie • mniej pomyłek",
    "url": "https://www.amazon.co.uk/s?k=RasPiO%20Portsplus%20GPIO%20Nak%C5%82adka%20opisowa%20GPIO%20&tag=marcinkorapro-21",
    "youtubePl": "Do szybkiego prototypowania używam płytki RasPiO Portsplus z czytelnym opisem GPIO.",
    "youtubeEn": "For quick prototyping I use a RasPiO Portsplus board with clearly labelled GPIO pins."
  },
  {
    "id": "speaker-usb",
    "name": "Mini External USB Stereo Speaker",
    "short": "Kompaktowy głośnik do prototypów",
    "category": "Audio",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "price": "£14.40",
    "accent": "pink",
    "spec": "USB • stereo • mała obudowa",
    "url": "https://www.amazon.co.uk/s?k=Mini%20External%20USB%20Stereo%20Speaker%20USB%20&tag=marcinkorapro-21",
    "youtubePl": "Dźwięk podczas testów zapewnia kompaktowy zewnętrzny głośnik stereo USB.",
    "youtubeEn": "A compact external USB stereo speaker provides audio during testing."
  },
  {
    "id": "camera-cable-300",
    "name": "Taśma kamery do Raspberry Pi 5 — 300 mm",
    "short": "Dłuższe połączenie kamery z komputerem",
    "category": "Połączenia",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "slate",
    "spec": "300 mm • złącze MIPI do Raspberry Pi 5 • elastyczna taśma",
    "url": "https://amzn.to/4x8qdPF",
    "youtubePl": "Kamera jest połączona z Raspberry Pi 5 elastyczną taśmą MIPI o długości 300 mm.",
    "youtubeEn": "The camera is connected to the Raspberry Pi 5 with a 300 mm flexible MIPI cable."
  },
  {
    "id": "usb-c-molex",
    "name": "Przewód USB-C → Molex 4-pin",
    "short": "Zasilanie urządzeń z gniazda Molex",
    "category": "Połączenia",
    "supplier": "Amazon",
    "project": "Warsztat",
    "status": "Mam",
    "accent": "slate",
    "spec": "USB-C • gniazdo Molex 4-pin • przewód zasilający",
    "url": "https://www.amazon.co.uk/s?k=Przew%C3%B3d%20USB-C%20%E2%86%92%20Molex%204-pin%20USB-C%20&tag=marcinkorapro-21",
    "youtubePl": "Do nietypowych połączeń zasilania używam przewodu USB-C z czteropinowym gniazdem Molex.",
    "youtubeEn": "For custom power connections I use a USB-C cable with a four-pin Molex socket."
  },
  {
    "id": "poe-header",
    "name": "PoE+ HAT Extra Tall Header Kit — 2×20 / 23.2 mm",
    "short": "40-pinowy przedłużacz użyty w stacku UPS + Pi 5 + Hailo",
    "category": "Połączenia",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Używam",
    "accent": "slate",
    "spec": "2×20 / 40 pinów • wysokość 23.2 mm • raster 2.54 mm • montaż wciskany • w Korze użyta część 40-pinowa",
    "url": "https://www.amazon.co.uk/s?k=PoE%2B%20HAT%20Extra%20Tall%20Header%20Kit%20%E2%80%94%202%C3%9720%20%2F%2023.2%20mm%202%C3%9720%20%2F%2040%20pin%C3%B3w%20&tag=marcinkorapro-21",
    "youtubePl": "W stacku UPS + Raspberry Pi 5 + Hailo wykorzystałem 40-pinową część wysokiego headera z zestawu Pi Hut. Specjalne cztery piny PoE nie były w tym montażu potrzebne.",
    "youtubeEn": "In the UPS + Raspberry Pi 5 + Hailo stack I used the 40-pin extra-tall header from the Pi Hut kit. The special four PoE pins were not needed for this build."
  },
  {
    "id": "pca9685",
    "name": "PCA9685 — 16 kanałów PWM",
    "short": "Sterownik serwomechanizmów",
    "category": "Sterowanie",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Używam",
    "price": "£4.99 / 2 szt.",
    "accent": "green",
    "spec": "16 kanałów • 12-bit PWM • magistrala I²C",
    "url": "https://www.amazon.co.uk/s?k=PCA9685%20%E2%80%94%2016%20kana%C5%82%C3%B3w%20PWM%2016%20kana%C5%82%C3%B3w%20&tag=marcinkorapro-21",
    "youtubePl": "Ruchem serwomechanizmów sterują 16-kanałowe moduły PCA9685 przez magistralę I²C.",
    "youtubeEn": "The servos are controlled by 16-channel PCA9685 modules over I²C."
  },
  {
    "id": "servo-controller-32ch",
    "name": "USB — 32-kanałowy sterownik serw",
    "short": "Jedna płytka dla 18 serw nóg Kory",
    "category": "Sterowanie",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "green",
    "spec": "32 kanały PWM • sterowanie przez USB • osobne zasilanie serw",
    "url": "https://www.amazon.co.uk/s?k=USB%20%E2%80%94%2032-kana%C5%82owy%20sterownik%20serw%2032%20kana%C5%82y%20PWM%20&tag=marcinkorapro-21",
    "youtubePl": "Osiemnastoma serwami nóg Kory steruje jedna 32-kanałowa płytka podłączana przez USB.",
    "youtubeEn": "Kora's 18 leg servos are controlled by one 32-channel board connected over USB."
  },
  {
    "id": "esp32c6",
    "name": "ESP32-C6 SuperMini",
    "short": "Mały kontroler Wi-Fi i Bluetooth",
    "category": "Sterowanie",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Używam",
    "price": "£2.95 / szt.",
    "accent": "green",
    "spec": "Wi-Fi 6 • Bluetooth 5 • RISC-V • kompaktowy format",
    "url": "https://www.amazon.co.uk/s?k=ESP32-C6%20SuperMini%20Wi-Fi%206%20&tag=marcinkorapro-21",
    "youtubePl": "Sterowanie niskopoziomowe realizuje kompaktowa płytka ESP32-C6 SuperMini.",
    "youtubeEn": "Low-level control is handled by a compact ESP32-C6 SuperMini board."
  },
  {
    "id": "esp32s3",
    "name": "ESP32-S3 N16R8",
    "short": "Kontroler z 16 MB Flash i 8 MB PSRAM",
    "category": "Sterowanie",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "price": "£3.99 / szt.",
    "accent": "green",
    "spec": "16 MB Flash • 8 MB PSRAM • Wi-Fi • Bluetooth",
    "url": "https://www.amazon.co.uk/s?k=ESP32-S3%20N16R8%2016%20MB%20Flash%20&tag=marcinkorapro-21",
    "youtubePl": "W prototypach używam ESP32-S3 N16R8 z 16 MB Flash i 8 MB PSRAM.",
    "youtubeEn": "My prototypes use ESP32-S3 N16R8 boards with 16 MB Flash and 8 MB PSRAM."
  },
  {
    "id": "esp32c3",
    "name": "ESP32-C3 SuperMini",
    "short": "Maleńka płytka do szybkich prototypów",
    "category": "Sterowanie",
    "supplier": "Amazon",
    "project": "Uniwersalne",
    "status": "Mam",
    "accent": "green",
    "spec": "RISC-V 160 MHz • Wi-Fi 2,4 GHz • Bluetooth 5 LE • USB-C • 4 MB Flash",
    "url": "https://www.amazon.co.uk/s?k=ESP32-C3%20SuperMini%20RISC-V%20160%20MHz%20&tag=marcinkorapro-21",
    "youtubePl": "Do małych układów sterujących używam kompaktowej płytki ESP32-C3 SuperMini z Wi-Fi i Bluetooth LE.",
    "youtubeEn": "For small control systems I use the compact ESP32-C3 SuperMini board with Wi-Fi and Bluetooth LE."
  },
  {
    "id": "huskylens",
    "name": "DFRobot HUSKYLENS — SEN0305",
    "short": "Wizja i rozpoznawanie obiektów w starszej Korze",
    "category": "Sensory",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Używam",
    "accent": "cyan",
    "spec": "Kendryte K210 • ekran IPS 2″ • twarze, obiekty, kolory, linie i kody • I²C / UART",
    "url": "https://www.amazon.co.uk/s?k=DFRobot%20HUSKYLENS%20%E2%80%94%20SEN0305%20Kendryte%20K210%20&tag=marcinkorapro-21",
    "youtubePl": "W jednej ze starszych wersji Kory moduł DFRobot HUSKYLENS rozpoznawał twarze, obiekty, kolory i linie.",
    "youtubeEn": "In one of Kora's earlier versions, the DFRobot HUSKYLENS module recognised faces, objects, colours and lines."
  },
  {
    "id": "dfrobot-voice",
    "name": "DFRobot DF2301Q — SEN0539",
    "short": "Rozpoznawanie poleceń głosowych bez internetu",
    "category": "Audio",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "pink",
    "spec": "121 poleceń wbudowanych • 17 własnych • I²C / UART • mikrofony i komunikaty głosowe",
    "url": "https://www.amazon.co.uk/s?k=DFRobot%20DF2301Q%20%E2%80%94%20SEN0539%20121%20polece%C5%84%20wbudowanych%20&tag=marcinkorapro-21",
    "youtubePl": "Polecenia głosowe może rozpoznawać lokalnie moduł DFRobot DF2301Q, bez połączenia z internetem.",
    "youtubeEn": "Voice commands can be recognised locally by the DFRobot DF2301Q module without an internet connection."
  },
  {
    "id": "dfrobot-tts",
    "name": "DFRobot Gravity: Text to Speech — DFR0760",
    "short": "Moduł odczytujący przesłany tekst przez wbudowany głośnik",
    "category": "Audio",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "pink",
    "spec": "Synteza tekstu na mowę po angielsku i chińsku • I²C / UART • wbudowany głośnik • 3,3–5 V",
    "url": "https://www.amazon.co.uk/s?k=DFRobot%20Gravity%3A%20Text%20to%20Speech%20%E2%80%94%20DFR0760%20Synteza%20tekstu%20na%20mow%C4%99%20po%20angielsku%20i%20chi%C5%84sku%20&tag=marcinkorapro-21",
    "youtubePl": "Do syntezy mowy używam modułu DFRobot DFR0760: wysyłam tekst przez I²C lub UART, a moduł odczytuje go przez wbudowany głośnik.",
    "youtubeEn": "For speech synthesis I use the DFRobot DFR0760: I send text over I²C or UART, and the module reads it through its built-in speaker."
  },
  {
    "id": "rplidar-c1",
    "name": "SLAMTEC RPLIDAR C1",
    "short": "Kompaktowy lidar posiadany do testów",
    "category": "Sensory",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "cyan",
    "spec": "360° • pomiar ToF • zasięg do 12 m • osobny od RPLIDAR A2 używanego obecnie w Korze",
    "url": "https://www.amazon.co.uk/s?k=SLAMTEC%20RPLIDAR%20C1%20360%C2%B0%20&tag=marcinkorapro-21",
    "youtubePl": "Do testów mam również kompaktowy lidar SLAMTEC RPLIDAR C1; obecna Kora korzysta z modelu RPLIDAR A2.",
    "youtubeEn": "I also own a compact SLAMTEC RPLIDAR C1 for testing; the current Kora system uses an RPLIDAR A2."
  },
  {
    "id": "vl53l1x",
    "name": "VL53L1X Time-of-Flight",
    "short": "Laserowy pomiar odległości",
    "category": "Sensory",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Używam",
    "accent": "cyan",
    "spec": "ToF • I²C • zasięg do 4 m",
    "url": "https://www.amazon.co.uk/s?k=VL53L1X%20Time-of-Flight%20ToF%20&tag=marcinkorapro-21",
    "youtubePl": "Odległość z przodu mierzy laserowy czujnik Time-of-Flight VL53L1X o zasięgu do 4 metrów.",
    "youtubeEn": "Front distance is measured by a VL53L1X Time-of-Flight sensor with a range of up to 4 metres."
  },
  {
    "id": "bmi160",
    "name": "BMI160 — IMU 6DoF",
    "short": "Akcelerometr i żyroskop",
    "category": "Sensory",
    "supplier": "Amazon",
    "project": "Roboty mobilne",
    "status": "Mam",
    "price": "£1.00 / szt.",
    "accent": "cyan",
    "spec": "6 osi • akcelerometr • żyroskop • I²C / SPI",
    "url": "https://www.amazon.co.uk/s?k=BMI160%20%E2%80%94%20IMU%206DoF%206%20osi%20&tag=marcinkorapro-21",
    "youtubePl": "Ruch i przechylenie mierzy sześcioosiowy moduł BMI160 z akcelerometrem i żyroskopem.",
    "youtubeEn": "Motion and tilt are measured by a six-axis BMI160 module with an accelerometer and gyroscope."
  },
  {
    "id": "apds9960",
    "name": "APDS-9960",
    "short": "Gesty, zbliżenie, kolor i światło",
    "category": "Sensory",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "price": "£2.00 / szt.",
    "accent": "cyan",
    "spec": "Gesty • zbliżenie • RGB • natężenie światła • I²C",
    "url": "https://www.amazon.co.uk/s?k=APDS-9960%20Gesty%20&tag=marcinkorapro-21",
    "youtubePl": "Gesty, zbliżenie i kolor światła wykrywa wielofunkcyjny czujnik APDS-9960.",
    "youtubeEn": "Gestures, proximity and light colour are detected by an APDS-9960 multifunction sensor."
  },
  {
    "id": "ld2410c",
    "name": "LD2410C — radar 24 GHz",
    "short": "Wykrywanie obecności człowieka",
    "category": "Sensory",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "cyan",
    "spec": "FMCW 24 GHz • wykrywa ruch i mikroruchy • UART / Bluetooth",
    "url": "https://www.amazon.co.uk/s?k=LD2410C%20%E2%80%94%20radar%2024%20GHz%20FMCW%2024%20GHz%20&tag=marcinkorapro-21",
    "youtubePl": "Obecność człowieka wykrywa radar FMCW LD2410C pracujący w paśmie 24 GHz.",
    "youtubeEn": "Human presence is detected by an LD2410C FMCW radar operating at 24 GHz."
  },
  {
    "id": "bts7960",
    "name": "BTS7960 — mostek H 43 A",
    "short": "Sterownik silników dużej mocy",
    "category": "Napędy",
    "supplier": "Amazon",
    "project": "Roboty mobilne",
    "status": "Mam",
    "price": "£8.19 / 2 szt.",
    "accent": "red",
    "spec": "Mostek H • do 43 A deklarowane przez sprzedawcę • PWM",
    "url": "https://www.amazon.co.uk/s?k=BTS7960%20%E2%80%94%20mostek%20H%2043%20A%20Mostek%20H%20&tag=marcinkorapro-21",
    "youtubePl": "Silnikami dużej mocy sterują moduły mostka H BTS7960.",
    "youtubeEn": "High-power motors are controlled by BTS7960 H-bridge modules."
  },
  {
    "id": "rds5180",
    "name": "RDS5180 — serwo 80 kg",
    "short": "Mocne serwo dwuosiowe",
    "category": "Napędy",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "red",
    "spec": "7.4 V • metalowe przekładnie • podwójny wał",
    "url": "https://www.amazon.co.uk/s?k=RDS5180%20%E2%80%94%20serwo%2080%20kg%207.4%20V%20&tag=marcinkorapro-21",
    "youtubePl": "Do ruchów wymagających dużego momentu wykorzystuję dwuosiowe serwo RDS5180 z metalową przekładnią.",
    "youtubeEn": "For high-torque movement I use an RDS5180 dual-shaft servo with metal gears."
  },
  {
    "id": "rds3115",
    "name": "RDS3115MG — serwo 17 kg",
    "short": "Serwo z wcześniejszej czteronożnej Kory",
    "category": "Napędy",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "red",
    "spec": "180° / 270° • metalowe przekładnie • podwójny wał",
    "url": "https://www.amazon.co.uk/s?k=RDS3115MG%20%E2%80%94%20serwo%2017%20kg%20180%C2%B0%20%2F%20270%C2%B0%20&tag=marcinkorapro-21",
    "youtubePl": "We wcześniejszej czteronożnej wersji Kory używałem dwuosiowych serw RDS3115MG z metalowymi przekładniami.",
    "youtubeEn": "An earlier four-legged version of Kora used RDS3115MG dual-shaft servos with metal gears."
  },
  {
    "id": "sg90",
    "name": "SG90 — mikroserwo 9 g",
    "short": "Małe i lekkie serwo 180°",
    "category": "Napędy",
    "supplier": "Amazon",
    "project": "Uniwersalne",
    "status": "Mam",
    "price": "£7.99 / 10 szt.",
    "accent": "red",
    "spec": "9 g • 180° • PWM • lekkie mechanizmy",
    "url": "https://www.amazon.co.uk/s?k=SG90%20%E2%80%94%20mikroserwo%209%20g%209%20g%20&tag=marcinkorapro-21",
    "youtubePl": "Lekkie mechanizmy poruszają popularne mikroserwa SG90 o masie 9 gramów.",
    "youtubeEn": "Lightweight mechanisms are moved by popular 9-gram SG90 micro servos."
  },
  {
    "id": "dc5v15a",
    "name": "Przetwornica DC-DC 5 V / 15 A",
    "short": "Zasilanie elektroniki z 12–24 V",
    "category": "Zasilanie",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "price": "£5.69 / szt.",
    "accent": "amber",
    "spec": "Wejście 12–24 V • wyjście 5 V • deklarowane 15 A",
    "url": "https://www.amazon.co.uk/s?k=Przetwornica%20DC-DC%205%20V%20%2F%2015%20A%20Wej%C5%9Bcie%2012%E2%80%9324%20V%20&tag=marcinkorapro-21",
    "youtubePl": "Napięcie instalacji 12–24 V obniża przetwornica DC-DC do 5 V dla elektroniki sterującej.",
    "youtubeEn": "A DC-DC converter steps the 12–24 V supply down to 5 V for the control electronics."
  },
  {
    "id": "dc-stepdown-10a",
    "name": "Przetwornica DC-DC 11,1 V → 5 V / 10 A",
    "short": "Osobny tor 5 V dla komputera i elektroniki",
    "category": "Zasilanie",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "amber",
    "spec": "Wejście z pakietu 3S 11,1 V • wyjście 5 V • deklarowane 10 A • nie zasila szyny serw 6 V",
    "url": "https://www.amazon.co.uk/s?k=Przetwornica%20DC-DC%2011%2C1%20V%20%E2%86%92%205%20V%20%2F%2010%20A%20Wej%C5%9Bcie%20z%20pakietu%203S%2011%2C1%20V%20&tag=marcinkorapro-21",
    "youtubePl": "Elektronika Kory ma osobny tor 5 V zasilany z pakietu 11,1 V przez przetwornicę DC-DC 10 A; serwa korzystają z oddzielnej szyny około 6 V.",
    "youtubeEn": "Kora's electronics use a separate 5 V rail supplied from the 11.1 V pack through a 10 A DC-DC converter; the servos use a separate rail at about 6 V."
  },
  {
    "id": "dcwide",
    "name": "Przetwornica DC-DC 12–90 V → 5 V",
    "short": "Szeroki zakres napięcia wejściowego",
    "category": "Zasilanie",
    "supplier": "Amazon",
    "project": "Roboty mobilne",
    "status": "Mam",
    "price": "£5.79",
    "accent": "amber",
    "spec": "Wejście 12–90 V • wyjście 5 V • deklarowane 10 A",
    "url": "https://www.amazon.co.uk/s?k=Przetwornica%20DC-DC%2012%E2%80%9390%20V%20%E2%86%92%205%20V%20Wej%C5%9Bcie%2012%E2%80%9390%20V%20&tag=marcinkorapro-21",
    "youtubePl": "Elektronikę zasilam przez szerokozakresową przetwornicę DC-DC 12–90 V na 5 V.",
    "youtubeEn": "The electronics are powered through a wide-input 12–90 V to 5 V DC-DC converter."
  },
  {
    "id": "ws2812matrix",
    "name": "Matryca WS2812B 16×16",
    "short": "Matryca używana do efektów świetlnych radia IR",
    "category": "Światło",
    "supplier": "Amazon",
    "project": "Radio IR",
    "status": "Używam",
    "price": "£5.40 / szt.",
    "accent": "blue",
    "spec": "256 pikseli • RGB • 5 V • indywidualne sterowanie",
    "url": "https://www.amazon.co.uk/s?k=Matryca%20WS2812B%2016%C3%9716%20256%20pikseli%20&tag=marcinkorapro-21",
    "youtubePl": "Efekty świetlne radia wyświetla matryca WS2812B 16×16 z 256 indywidualnie sterowanymi diodami RGB.",
    "youtubeEn": "The radio's lighting effects are displayed on a 16×16 WS2812B matrix with 256 individually addressable RGB LEDs."
  },
  {
    "id": "led-ring16",
    "name": "Pierścień LED RGB — 16 diod",
    "short": "Sygnalizacja stanu i animacje świetlne Kory",
    "category": "Światło",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Mam",
    "accent": "blue",
    "spec": "16 adresowalnych diod RGB • zasilanie 5 V • sterowanie szeregowe",
    "url": "https://www.amazon.co.uk/s?k=Pier%C5%9Bcie%C5%84%20LED%20RGB%20%E2%80%94%2016%20diod%2016%20adresowalnych%20diod%20RGB%20&tag=marcinkorapro-21",
    "youtubePl": "Stan i reakcje Kory może sygnalizować pierścień z 16 adresowalnymi diodami RGB.",
    "youtubeEn": "Kora's state and reactions can be indicated by a ring of 16 individually addressable RGB LEDs."
  },
  {
    "id": "rgb-strip",
    "name": "Pasek LED RGB",
    "short": "Pasek używany w projekcie lampy i zegara",
    "category": "Światło",
    "supplier": "Amazon",
    "project": "Lampa i zegar",
    "status": "Używam",
    "accent": "blue",
    "spec": "Diody RGB • kanały R/G/B • elastyczna taśma • efekty świetlne",
    "url": "https://www.amazon.co.uk/s?k=Pasek%20LED%20RGB%20Diody%20RGB%20&tag=marcinkorapro-21",
    "youtubePl": "Efekty świetlne lampy i zegara realizuje elastyczny pasek LED RGB.",
    "youtubeEn": "The lamp and clock lighting effects are produced by a flexible RGB LED strip."
  },
  {
    "id": "pcm5102",
    "name": "PCM5102A — przetwornik I²S DAC",
    "short": "Cyfrowe audio dla Raspberry Pi i ESP32",
    "category": "Audio",
    "supplier": "Amazon",
    "project": "Audio",
    "status": "Używam",
    "price": "£1.60",
    "accent": "pink",
    "spec": "I²S • wyjście stereo analog • 32-bit DAC",
    "url": "https://www.amazon.co.uk/s?k=PCM5102A%20%E2%80%94%20przetwornik%20I%C2%B2S%20DAC%20I%C2%B2S%20&tag=marcinkorapro-21",
    "youtubePl": "Cyfrowy dźwięk I²S zamienia na sygnał analogowy moduł DAC PCM5102A.",
    "youtubeEn": "A PCM5102A DAC converts the digital I²S audio stream into an analogue stereo signal."
  },
  {
    "id": "inmp441",
    "name": "INMP441 — mikrofon I²S",
    "short": "Cyfrowy mikrofon MEMS",
    "category": "Audio",
    "supplier": "Amazon",
    "project": "Audio",
    "status": "Mam",
    "price": "£2.09 / szt.",
    "accent": "pink",
    "spec": "MEMS • I²S • do ESP32 • niski pobór mocy",
    "url": "https://www.amazon.co.uk/s?k=INMP441%20%E2%80%94%20mikrofon%20I%C2%B2S%20MEMS%20&tag=marcinkorapro-21",
    "youtubePl": "Dźwięk rejestruje cyfrowy mikrofon MEMS INMP441 po magistrali I²S.",
    "youtubeEn": "Audio is captured by an INMP441 digital MEMS microphone over I²S."
  },
  {
    "id": "ili9341",
    "name": "Wyświetlacz TFT 2.8″ ILI9341",
    "short": "Kolorowy ekran dotykowy SPI",
    "category": "Wyświetlacze",
    "supplier": "Amazon",
    "project": "Uniwersalne",
    "status": "Mam",
    "price": "£4.69 / szt.",
    "accent": "blue",
    "spec": "240×320 px • SPI • panel dotykowy",
    "url": "https://www.amazon.co.uk/s?k=Wy%C5%9Bwietlacz%20TFT%202.8%E2%80%B3%20ILI9341%20240%C3%97320%20px%20&tag=marcinkorapro-21",
    "youtubePl": "Interfejs wyświetlam na kolorowym ekranie dotykowym TFT 2,8 cala z kontrolerem ILI9341.",
    "youtubeEn": "The interface is shown on a 2.8-inch colour TFT touchscreen driven by the ILI9341 controller."
  },
  {
    "id": "oled12864",
    "name": "OLED 0.96″ 128×64 — SSD1306",
    "short": "Mały wyświetlacz, który uwielbiam",
    "category": "Wyświetlacze",
    "supplier": "Amazon",
    "project": "Kora / VEGA",
    "status": "Używam",
    "accent": "blue",
    "spec": "128×64 px • OLED • I²C • kontroler SSD1306 • 3,3–5 V",
    "url": "https://www.amazon.co.uk/dp/B07Z8QBRWN?tag=marcinkorapro-21",
    "youtubePl": "Informacje i proste animacje pokazuję na moim ulubionym małym wyświetlaczu OLED 128×64 z kontrolerem SSD1306.",
    "youtubeEn": "I display information and simple animations on my favourite small 128×64 OLED screen driven by the SSD1306 controller."
  },
  {
    "id": "ir-sensor",
    "name": "Czujnik podczerwieni IR",
    "short": "Bezdotykowe wykrywanie dłoni i przeszkód",
    "category": "Sensory",
    "supplier": "Amazon",
    "project": "Audio",
    "status": "Używam",
    "accent": "cyan",
    "spec": "Nadajnik i odbiornik IR • regulowana czułość • wyjście cyfrowe",
    "url": "https://www.amazon.co.uk/s?k=Czujnik%20podczerwieni%20IR%20Nadajnik%20i%20odbiornik%20IR%20&tag=marcinkorapro-21",
    "youtubePl": "Radiem steruję bezdotykowo za pomocą czujników podczerwieni wykrywających ruch dłoni.",
    "youtubeEn": "I control the radio without touching it by using infrared sensors that detect hand movement."
  },
  {
    "id": "dupont",
    "name": "Przewody Dupont 10–30 cm",
    "short": "Komplet męski–męski, męski–żeński i żeński–żeński",
    "category": "Połączenia",
    "supplier": "Amazon",
    "project": "Warsztat",
    "status": "Mam",
    "accent": "slate",
    "spec": "40 żył • 10 / 20 / 30 cm • MM + MF + FF",
    "url": "https://www.amazon.co.uk/s?k=Przewody%20Dupont%2010%E2%80%9330%20cm%2040%20%C5%BCy%C5%82%20&tag=marcinkorapro-21",
    "youtubePl": "Połączenia prototypowe wykonuję kompletami przewodów Dupont: męski–męski, męski–żeński i żeński–żeński.",
    "youtubeEn": "Prototype connections are made with male-to-male, male-to-female and female-to-female Dupont jumper wire sets."
  },
  {
    "id": "powerbank-18650",
    "name": "Obudowy powerbank 1–4× 18650",
    "short": "Modułowe obudowy do ogniw 18650",
    "category": "Zasilanie",
    "supplier": "Amazon",
    "project": "Warsztat",
    "status": "Mam",
    "accent": "amber",
    "spec": "Warianty 1 / 2 / 3 / 4 ogniwa • obudowa z elektroniką USB • ogniwa osobno",
    "url": "https://www.amazon.co.uk/s?k=Obudowy%20powerbank%201%E2%80%934%C3%97%2018650%20Warianty%201%20%2F%202%20%2F%203%20%2F%204%20ogniwa%20&tag=marcinkorapro-21",
    "youtubePl": "Do przenośnego zasilania prototypów używam obudów powerbank mieszczących od jednego do czterech ogniw 18650.",
    "youtubeEn": "For portable prototype power I use power-bank enclosures holding between one and four 18650 cells."
  },
  {
    "id": "xh254",
    "name": "Złącza JST-XH 2.54 mm",
    "short": "Przewody i gniazda czteropinowe",
    "category": "Połączenia",
    "supplier": "Amazon",
    "project": "Warsztat",
    "status": "Mam",
    "price": "£1.14 / 5 kpl.",
    "accent": "slate",
    "spec": "Raster 2.54 mm • 4 piny • przewody 10 cm",
    "url": "https://www.amazon.co.uk/s?k=Z%C5%82%C4%85cza%20JST-XH%202.54%20mm%20Raster%202.54%20mm%20&tag=marcinkorapro-21",
    "youtubePl": "Moduły łączę rozłącznymi złączami JST-XH 2,54 mm.",
    "youtubeEn": "Modules are connected with detachable 2.54 mm JST-XH connectors."
  },
  {
    "id": "cnc-hrc68",
    "name": "Frez węglikowy HRC68 — 4 ostrza",
    "short": "Frez do precyzyjnej obróbki metalu",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£3.02",
    "accent": "green",
    "spec": "1,5 mm • chwyt 4 mm • długość 50 mm • 4 ostrza",
    "url": "https://www.amazon.co.uk/s?k=Frez%20w%C4%99glikowy%20HRC68%20%E2%80%94%204%20ostrza%201%2C5%20mm%20&tag=marcinkorapro-21",
    "youtubePl": "Do precyzyjnej obróbki używam czteroostrzowego frezu węglikowego HRC68 o średnicy 1,5 mm.",
    "youtubeEn": "For precision machining I use a 1.5 mm HRC68 four-flute carbide end mill."
  },
  {
    "id": "cnc-grbl2",
    "name": "Sterownik GRBL 32-bit — 2 osie",
    "short": "Płyta sterująca grawerką laserową",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£14.80",
    "accent": "green",
    "spec": "32-bit MCU • USB-C • 2 osie • sterowniki zintegrowane",
    "url": "https://www.amazon.co.uk/s?k=Sterownik%20GRBL%2032-bit%20%E2%80%94%202%20osie%2032-bit%20MCU%20&tag=marcinkorapro-21",
    "youtubePl": "Dwoma osiami grawerki steruje 32-bitowa płyta GRBL z portem USB-C.",
    "youtubeEn": "A 32-bit GRBL board with USB-C controls the engraver's two axes."
  },
  {
    "id": "cnc-rotary",
    "name": "Moduł obrotowy TwoTrees",
    "short": "Grawerowanie przedmiotów cylindrycznych",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£30.95",
    "accent": "red",
    "spec": "Napęd rolkowy • oś obrotowa • puszki i elementy cylindryczne",
    "url": "https://www.amazon.co.uk/s?k=Modu%C5%82%20obrotowy%20TwoTrees%20Nap%C4%99d%20rolkowy%20&tag=marcinkorapro-21",
    "youtubePl": "Moduł obrotowy TwoTrees pozwala grawerować puszki i inne cylindryczne przedmioty.",
    "youtubeEn": "The TwoTrees rotary module enables engraving on cans and other cylindrical objects."
  },
  {
    "id": "cnc-z-axis",
    "name": "Moduł osi Z 2040V",
    "short": "Regulacja wysokości głowicy laserowej",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£15.47",
    "accent": "red",
    "spec": "Profil 2040V • regulacja osi Z • uchwyt głowicy",
    "url": "https://www.amazon.co.uk/s?k=Modu%C5%82%20osi%20Z%202040V%20Profil%202040V%20&tag=marcinkorapro-21",
    "youtubePl": "Moduł osi Z umożliwia precyzyjne ustawienie wysokości głowicy względem materiału.",
    "youtubeEn": "The Z-axis module provides precise adjustment of the head height above the workpiece."
  },
  {
    "id": "cnc-psu24",
    "name": "Zasilacz na szynę DIN — 24 V / 2,5 A",
    "short": "Zasilanie sterowania i napędów",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£6.14",
    "accent": "amber",
    "spec": "60 W • 24 V DC • 2,5 A • montaż na szynie DIN",
    "url": "https://www.amazon.co.uk/s?k=Zasilacz%20na%20szyn%C4%99%20DIN%20%E2%80%94%2024%20V%20%2F%202%2C5%20A%2060%20W%20&tag=marcinkorapro-21",
    "youtubePl": "Sterowanie maszyny zasila kompaktowy zasilacz 24 V / 2,5 A montowany na szynie DIN.",
    "youtubeEn": "The machine control system is powered by a compact 24 V / 2.5 A DIN-rail power supply."
  },
  {
    "id": "cnc-endmill-2f",
    "name": "Frez DREANIQUE 2 mm — 2 ostrza",
    "short": "Frez prosty do drewna, MDF i tworzyw",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Używam",
    "price": "£1.65 / szt.",
    "accent": "green",
    "spec": "2 mm • długość robocza 17 / 22 mm • węglik spiekany",
    "url": "https://www.amazon.co.uk/s?k=Frez%20DREANIQUE%202%20mm%20%E2%80%94%202%20ostrza%202%20mm%20&tag=marcinkorapro-21",
    "youtubePl": "Do wycinania i grawerowania używam dwuostrzowych frezów DREANIQUE o średnicy 2 mm.",
    "youtubeEn": "For cutting and engraving I use 2 mm DREANIQUE two-flute carbide end mills."
  },
  {
    "id": "cnc-dust-shoe",
    "name": "Szczotka odciągu wrzeciona — 65 mm",
    "short": "Zbieranie pyłu bezpośrednio przy frezie",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Używam",
    "price": "£12.78",
    "accent": "slate",
    "spec": "Mocowanie 65 mm • szczotka ochronna • króciec odciągu",
    "url": "https://www.amazon.co.uk/s?k=Szczotka%20odci%C4%85gu%20wrzeciona%20%E2%80%94%2065%20mm%20Mocowanie%2065%20mm%20&tag=marcinkorapro-21",
    "youtubePl": "Szczotka odciągu o średnicy 65 mm zbiera pył bezpośrednio wokół wrzeciona.",
    "youtubeEn": "A 65 mm spindle dust shoe collects debris directly around the cutter."
  },
  {
    "id": "cnc-controller4",
    "name": "Sterownik CNC GRBL — 4 osie",
    "short": "Główna płyta sterowania XYZA",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Używam",
    "price": "£51.76",
    "accent": "violet",
    "spec": "32-bit MCU • osie X/Y/Z/A • 4× DRV8825 • sterowanie wrzecionem do 500 W",
    "url": "https://www.amazon.co.uk/s?k=Sterownik%20CNC%20GRBL%20%E2%80%94%204%20osie%2032-bit%20MCU%20&tag=marcinkorapro-21",
    "youtubePl": "Ruchem osi X, Y, Z i A steruje 32-bitowa płyta GRBL z czterema sterownikami DRV8825.",
    "youtubeEn": "A 32-bit GRBL board with four DRV8825 drivers controls the X, Y, Z and A axes."
  },
  {
    "id": "cnc-nema17",
    "name": "NEMA17 — 60 mm / 71 Ncm",
    "short": "Silnik krokowy do osi CNC",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Używam",
    "accent": "red",
    "spec": "2 fazy • 1,8° • 1,8 A • 0,71 Nm / 71 Ncm • korpus 60 mm • przewód 4-żyłowy",
    "url": "https://www.amazon.co.uk/s?k=NEMA17%20%E2%80%94%2060%20mm%20%2F%2071%20Ncm%202%20fazy%20&tag=marcinkorapro-21",
    "youtubePl": "Osie maszyny napędzają silniki krokowe NEMA17 o momencie 71 Ncm i prądzie 1,8 A na fazę.",
    "youtubeEn": "The machine axes are driven by NEMA17 stepper motors rated at 71 Ncm and 1.8 A per phase."
  },
  {
    "id": "cnc-sbr",
    "name": "Prowadnice liniowe SBR + wózki UU/LUU",
    "short": "Sztywne prowadzenie osi frezarki",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Używam",
    "accent": "slate",
    "spec": "SBR10 / 12 / 16 / 20 • wózki SBRxxUU i SBRxxLUU • podparte wałki liniowe",
    "url": "https://www.amazon.co.uk/s?k=Prowadnice%20liniowe%20SBR%20%2B%20w%C3%B3zki%20UU%2FLUU%20SBR10%20%2F%2012%20%2F%2016%20%2F%2020%20&tag=marcinkorapro-21",
    "youtubePl": "Ruch osi frezarki prowadzą podparte prowadnice liniowe SBR z wózkami kulkowymi UU i LUU.",
    "youtubeEn": "The router axes run on supported SBR linear rails with UU and LUU ball-bearing blocks."
  },
  {
    "id": "cnc-spindle-vfd",
    "name": "Wrzeciono 800 W + VFD 1,5 kW",
    "short": "Główny napęd frezarki z regulacją obrotów",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Używam",
    "price": "£157.12",
    "accent": "violet",
    "spec": "Zestaw 220 V • wrzeciono 800 W • falownik 1,5 kW • uchwyt ER11",
    "url": "https://www.amazon.co.uk/s?k=Wrzeciono%20800%20W%20%2B%20VFD%201%2C5%20kW%20Zestaw%20220%20V%20&tag=marcinkorapro-21",
    "youtubePl": "Frezarkę napędza wrzeciono 800 W sterowane falownikiem VFD 1,5 kW, który pozwala regulować prędkość obrotową.",
    "youtubeEn": "The router uses an 800 W spindle controlled by a 1.5 kW VFD for adjustable spindle speed."
  },
  {
    "id": "cnc-pump",
    "name": "Pompa chłodzenia wrzeciona — 80 W",
    "short": "Obieg wody dla chłodzonego wrzeciona",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Używam",
    "accent": "cyan",
    "spec": "80 W • wysokość podnoszenia 3,5 m • chłodzenie wodne wrzecion 1,5 / 2,2 kW",
    "url": "https://www.amazon.co.uk/s?k=Pompa%20ch%C5%82odzenia%20wrzeciona%20%E2%80%94%2080%20W%2080%20W%20&tag=marcinkorapro-21",
    "youtubePl": "Temperaturę wrzeciona utrzymuje obieg chłodzenia wodnego z pompą 80 W o wysokości podnoszenia 3,5 metra.",
    "youtubeEn": "Spindle temperature is controlled by a water-cooling loop with an 80 W pump rated for a 3.5-metre head."
  },
  {
    "id": "cnc-bits",
    "name": "Frezy grawerskie 0,8 / 3,175 mm — 10 szt.",
    "short": "Tytanowane frezy do grawerowania i PCB",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£4.39",
    "accent": "green",
    "spec": "10 sztuk • ostrze 0,8 mm • chwyt 3,175 mm • węglik z powłoką tytanową",
    "url": "https://www.amazon.co.uk/s?k=Frezy%20grawerskie%200%2C8%20%2F%203%2C175%20mm%20%E2%80%94%2010%20szt.%2010%20sztuk%20&tag=marcinkorapro-21",
    "youtubePl": "Do drobnego grawerowania i obróbki PCB używam tytanowanych frezów węglikowych z chwytem 3,175 mm.",
    "youtubeEn": "For fine engraving and PCB machining I use titanium-coated carbide cutters with a 3.175 mm shank."
  },
  {
    "id": "cnc-stc1000",
    "name": "Regulator temperatury STC-1000",
    "short": "Sterowanie grzaniem albo chłodzeniem",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "accent": "amber",
    "spec": "Czujnik temperatury • wyświetlacz LED • wyjścia grzanie / chłodzenie • przekaźniki 10 A",
    "url": "https://www.amazon.co.uk/s?k=Regulator%20temperatury%20STC-1000%20Czujnik%20temperatury%20&tag=marcinkorapro-21",
    "youtubePl": "Temperaturę układu kontroluje regulator STC-1000 z osobnymi wyjściami dla grzania i chłodzenia.",
    "youtubeEn": "System temperature is controlled by an STC-1000 regulator with separate heating and cooling outputs."
  },
  {
    "id": "cnc-c3018-upgrade",
    "name": "Zestaw prowadzenia CNC 3018 — SCV12VUU / T8",
    "short": "Łożyska i śruba do modernizacji osi",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "accent": "slate",
    "spec": "Łożyska SCV12VUU • wałki 10 / 12 mm • śruba pociągowa T8 • skok 4 mm",
    "url": "https://www.amazon.co.uk/s?k=Zestaw%20prowadzenia%20CNC%203018%20%E2%80%94%20SCV12VUU%20%2F%20T8%20%C5%81o%C5%BCyska%20SCV12VUU%20&tag=marcinkorapro-21",
    "youtubePl": "Modernizację osi CNC 3018 wykonałem z użyciem łożysk liniowych SCV12VUU i śruby pociągowej T8.",
    "youtubeEn": "I upgraded the CNC 3018 axis using SCV12VUU linear bearings and a T8 lead screw."
  },
  {
    "id": "cnc-mks-dlc32",
    "name": "MKS DLC32 V2.1 + TS24-R",
    "short": "Sterownik GRBL offline z małym ekranem",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "accent": "violet",
    "spec": "ESP32 • GRBL • Wi-Fi • karta microSD • ekran TS24-R • sterowanie offline",
    "url": "https://www.amazon.co.uk/s?k=MKS%20DLC32%20V2.1%20%2B%20TS24-R%20ESP32%20&tag=marcinkorapro-21",
    "youtubePl": "Sterownik MKS DLC32 V2.1 z ekranem TS24-R pozwala obsługiwać maszynę i uruchamiać pliki bez komputera.",
    "youtubeEn": "The MKS DLC32 V2.1 controller with a TS24-R display can operate the machine and run files without a computer."
  },
  {
    "id": "cnc-spindle-clamp",
    "name": "Aluminiowy uchwyt wrzeciona 52 / 65 / 80 mm",
    "short": "Sztywne mocowanie silnika na osi Z",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "accent": "slate",
    "spec": "Aluminium • średnice 52 / 65 / 80 mm • dzielony zacisk • cztery śruby",
    "url": "https://www.amazon.co.uk/s?k=Aluminiowy%20uchwyt%20wrzeciona%2052%20%2F%2065%20%2F%2080%20mm%20Aluminium%20&tag=marcinkorapro-21",
    "youtubePl": "Wrzeciono jest zamocowane na osi Z w sztywnym, aluminiowym uchwycie zaciskowym.",
    "youtubeEn": "The spindle is secured to the Z axis with a rigid aluminium clamp mount."
  },
  {
    "id": "cnc-z-axis52",
    "name": "Aluminiowy moduł osi Z CNC 3018 — 52 mm",
    "short": "Kompletna oś z prowadnicami i śrubą",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "accent": "red",
    "spec": "Mocowanie wrzeciona 52 mm • silnik NEMA17 • prowadnice liniowe • aluminiowy stół przesuwny",
    "url": "https://www.amazon.co.uk/s?k=Aluminiowy%20modu%C5%82%20osi%20Z%20CNC%203018%20%E2%80%94%2052%20mm%20Mocowanie%20wrzeciona%2052%20mm%20&tag=marcinkorapro-21",
    "youtubePl": "Moduł osi Z CNC 3018 łączy silnik NEMA17, prowadnice liniowe i aluminiowe mocowanie wrzeciona 52 mm.",
    "youtubeEn": "The CNC 3018 Z-axis module combines a NEMA17 motor, linear guides and a 52 mm aluminium spindle mount."
  },
  {
    "id": "relay-5v",
    "name": "Moduły przekaźnikowe 5 V — 2 / 4 kanały",
    "short": "Sterowanie kilkoma odbiornikami z mikrokontrolera",
    "category": "Sterowanie",
    "supplier": "Amazon",
    "project": "Uniwersalne",
    "status": "Mam",
    "price": "£3.14–£3.95",
    "accent": "green",
    "spec": "5 V • warianty 2- i 4-kanałowe • sterowanie z Arduino, ESP32 lub Raspberry Pi",
    "url": "https://www.amazon.co.uk/s?k=Modu%C5%82y%20przeka%C5%BAnikowe%205%20V%20%E2%80%94%202%20%2F%204%20kana%C5%82y%205%20V%20&tag=marcinkorapro-21",
    "youtubePl": "Do sterowania kilkoma odbiornikami używam dwu- i czterokanałowych modułów przekaźnikowych 5 V.",
    "youtubeEn": "For switching several loads I use two- and four-channel 5 V relay modules."
  },
  {
    "id": "esp32s3-expansion",
    "name": "Płytka rozszerzeń ESP32-S3 — 44 piny",
    "short": "Czytelne wyprowadzenie pinów do prototypowania",
    "category": "Sterowanie",
    "supplier": "Amazon",
    "project": "Warsztat",
    "status": "Mam",
    "price": "£5.27",
    "accent": "green",
    "spec": "44 piny • zgodny układ wyprowadzeń • płytka rozszerzająca do ESP32-S3",
    "url": "https://www.amazon.co.uk/s?k=P%C5%82ytka%20rozszerze%C5%84%20ESP32-S3%20%E2%80%94%2044%20piny%2044%20piny%20&tag=marcinkorapro-21",
    "youtubePl": "Do prototypowania z ESP32-S3 używam 44-pinowej płytki rozszerzeń z czytelnymi wyprowadzeniami.",
    "youtubeEn": "For ESP32-S3 prototyping I use a 44-pin expansion board with clearly exposed connections."
  },
  {
    "id": "tp4056",
    "name": "TP4056 — ładowarka Li-ion 1 A z ochroną",
    "short": "Ładowanie pojedynczego ogniwa 3,7 V",
    "category": "Zasilanie",
    "supplier": "Amazon",
    "project": "Warsztat",
    "status": "Mam",
    "price": "£3.14",
    "accent": "amber",
    "spec": "Micro USB • 1 A • pojedyncze ogniwo Li-ion 3,7 V • układ ochronny",
    "url": "https://www.amazon.co.uk/s?k=TP4056%20%E2%80%94%20%C5%82adowarka%20Li-ion%201%20A%20z%20ochron%C4%85%20Micro%20USB%20&tag=marcinkorapro-21",
    "youtubePl": "Pojedyncze ogniwa Li-ion 3,7 V ładuję modułem TP4056 1 A z wejściem Micro USB i układem ochronnym.",
    "youtubeEn": "I charge individual 3.7 V Li-ion cells with a 1 A TP4056 module featuring Micro USB input and protection."
  },
  {
    "id": "sunlu-resin",
    "name": "SUNLU — żywica 405 nm, 1 kg",
    "short": "Materiały ABS-like do druku żywicznego",
    "category": "Druk 3D",
    "supplier": "Amazon",
    "project": "Druk 3D",
    "status": "Używałem",
    "price": "£19.25–£19.44 / 1 kg",
    "accent": "violet",
    "spec": "405 nm • pomarańczowa ABS-like • biała water-washable ABS-like • opakowania 1 kg",
    "url": "https://www.amazon.co.uk/s?k=SUNLU%20%E2%80%94%20%C5%BCywica%20405%20nm%2C%201%20kg%20405%20nm%20&tag=marcinkorapro-21",
    "youtubePl": "Do wydruków żywicznych używałem żywic SUNLU 405 nm: pomarańczowej ABS-like oraz białej, zmywalnej wodą ABS-like.",
    "youtubeEn": "For resin printing I used SUNLU 405 nm resins: orange ABS-like and white water-washable ABS-like."
  },
  {
    "id": "liion-charger-2slot",
    "name": "Ładowarka USB do ogniw Li-ion — 2 gniazda",
    "short": "Proste ładowanie dwóch ogniw 3,7 V",
    "category": "Zasilanie",
    "supplier": "Amazon",
    "project": "Warsztat",
    "status": "Mam",
    "price": "£3.99",
    "accent": "amber",
    "spec": "USB • 2 gniazda • ogniwa Li-ion 3,7 V",
    "url": "https://www.amazon.co.uk/s?k=%C5%81adowarka%20USB%20do%20ogniw%20Li-ion%20%E2%80%94%202%20gniazda%20USB%20&tag=marcinkorapro-21",
    "youtubePl": "Do prostego ładowania dwóch ogniw Li-ion 3,7 V używam dwugniazdowej ładowarki USB.",
    "youtubeEn": "For simple charging of two 3.7 V Li-ion cells I use a dual-slot USB charger."
  },
  {
    "id": "a4988",
    "name": "A4988 — sterownik silnika krokowego",
    "short": "Moduł napędu osi CNC i drukarek 3D",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£3.79 / szt.",
    "accent": "red",
    "spec": "Sterownik silnika bipolarnego • regulacja prądu • mikrokroki • format zgodny z popularnymi shieldami CNC",
    "url": "https://www.amazon.co.uk/s?k=A4988%20%E2%80%94%20sterownik%20silnika%20krokowego%20Sterownik%20silnika%20bipolarnego%20&tag=marcinkorapro-21",
    "youtubePl": "Do sterowania silnikami krokowymi mam moduły A4988 z regulacją prądu i obsługą mikrokroków.",
    "youtubeEn": "For stepper-motor control I have A4988 modules with current adjustment and microstepping support."
  },
  {
    "id": "esp32-wroom-usbc",
    "name": "ESP32-WROOM-32 — płytka USB-C",
    "short": "Klasyczna płytka Wi-Fi i Bluetooth",
    "category": "Sterowanie",
    "supplier": "Amazon",
    "project": "Uniwersalne",
    "status": "Mam",
    "price": "£5.29",
    "accent": "green",
    "spec": "ESP32-WROOM-32 • USB-C • dwurdzeniowy układ • Wi-Fi • Bluetooth",
    "url": "https://www.amazon.co.uk/s?k=ESP32-WROOM-32%20%E2%80%94%20p%C5%82ytka%20USB-C%20ESP32-WROOM-32%20&tag=marcinkorapro-21",
    "youtubePl": "W wielu prototypach używam płytki ESP32-WROOM-32 z USB-C, Wi-Fi i Bluetooth.",
    "youtubeEn": "In many prototypes I use an ESP32-WROOM-32 development board with USB-C, Wi-Fi and Bluetooth."
  },
  {
    "id": "esp32-nodemcu-38",
    "name": "ESP32 NodeMCU — 38 pinów",
    "short": "Płytki rozwojowe do większych prototypów",
    "category": "Sterowanie",
    "supplier": "Amazon",
    "project": "Uniwersalne",
    "status": "Mam",
    "price": "£11.04 / 2 szt.",
    "accent": "green",
    "spec": "38 pinów • Wi-Fi • Bluetooth • zestaw 2 płytek",
    "url": "https://www.amazon.co.uk/s?k=ESP32%20NodeMCU%20%E2%80%94%2038%20pin%C3%B3w%2038%20pin%C3%B3w%20&tag=marcinkorapro-21",
    "youtubePl": "Do prototypów wymagających większej liczby wyprowadzeń mam 38-pinowe płytki ESP32 NodeMCU.",
    "youtubeEn": "For prototypes needing more exposed pins I have 38-pin ESP32 NodeMCU development boards."
  },
  {
    "id": "ir-torch-850",
    "name": "Latarka podczerwona 850 nm — 3 W",
    "short": "Doświetlenie dla kamery nocnej",
    "category": "Światło",
    "supplier": "Amazon",
    "project": "Uniwersalne",
    "status": "Mam",
    "price": "£14.10",
    "accent": "slate",
    "spec": "850 nm • 3 W • światło niewidoczne dla oka • współpraca z kamerami czułymi na IR",
    "url": "https://www.amazon.co.uk/s?k=Latarka%20podczerwona%20850%20nm%20%E2%80%94%203%20W%20850%20nm%20&tag=marcinkorapro-21",
    "youtubePl": "Do testów obrazu nocnego mam latarkę podczerwoną 850 nm o mocy 3 W.",
    "youtubeEn": "For night-vision testing I have a 3 W, 850 nm infrared torch."
  },
  {
    "id": "pc-speakers-rgb",
    "name": "Mini głośniki stereo RGB — USB / 3,5 mm",
    "short": "Kompaktowy dźwięk i podświetlenie do stanowiska",
    "category": "Audio",
    "supplier": "Amazon",
    "project": "Audio",
    "status": "Mam",
    "price": "£9.99",
    "accent": "pink",
    "spec": "Stereo • wejście audio 3,5 mm • zasilanie USB • podświetlenie RGB",
    "url": "https://www.amazon.co.uk/s?k=Mini%20g%C5%82o%C5%9Bniki%20stereo%20RGB%20%E2%80%94%20USB%20%2F%203%2C5%20mm%20Stereo%20&tag=marcinkorapro-21",
    "youtubePl": "Do testów audio mam kompaktowe głośniki stereo z wejściem 3,5 mm, zasilaniem USB i podświetleniem RGB.",
    "youtubeEn": "For audio testing I have compact stereo speakers with 3.5 mm input, USB power and RGB lighting."
  },
  {
    "id": "ttp223",
    "name": "TTP223 — pojemnościowy przycisk dotykowy",
    "short": "Mały sensor dotyku do prostych interfejsów",
    "category": "Sensory",
    "supplier": "Amazon",
    "project": "Uniwersalne",
    "status": "Mam",
    "accent": "cyan",
    "spec": "2 moduły • dotyk pojemnościowy • tryb chwilowy lub zatrzaskowy",
    "url": "https://www.amazon.co.uk/s?k=TTP223%20%E2%80%94%20pojemno%C5%9Bciowy%20przycisk%20dotykowy%202%20modu%C5%82y%20&tag=marcinkorapro-21",
    "youtubePl": "Do prostych interfejsów dotykowych mam dwa miniaturowe moduły pojemnościowe TTP223.",
    "youtubeEn": "For simple touch interfaces I have two miniature TTP223 capacitive modules."
  },
  {
    "id": "dfplayer-mini",
    "name": "DFPlayer Mini — MP3-TF-16P",
    "short": "Odtwarzanie dźwięków i komunikatów z karty",
    "category": "Audio",
    "supplier": "Amazon",
    "project": "Audio",
    "status": "Mam",
    "accent": "pink",
    "spec": "Moduł MP3 • gniazdo karty TF / microSD • sterowanie z mikrokontrolera",
    "url": "https://www.amazon.co.uk/s?k=DFPlayer%20Mini%20%E2%80%94%20MP3-TF-16P%20Modu%C5%82%20MP3%20&tag=marcinkorapro-21",
    "youtubePl": "Dźwięki i nagrane komunikaty mogę odtwarzać z karty microSD przez moduł DFPlayer Mini.",
    "youtubeEn": "I can play sounds and recorded prompts from a microSD card through a DFPlayer Mini module."
  },
  {
    "id": "mg90s",
    "name": "MG90S — mikroserwo 9 g z metalową przekładnią",
    "short": "Małe serwo do lekkich mechanizmów",
    "category": "Napędy",
    "supplier": "Amazon",
    "project": "Roboty mobilne",
    "status": "Mam",
    "accent": "red",
    "spec": "9 g • metalowa przekładnia • 6 sztuk • zastosowania robotyczne i RC",
    "url": "https://www.amazon.co.uk/s?k=MG90S%20%E2%80%94%20mikroserwo%209%20g%20z%20metalow%C4%85%20przek%C5%82adni%C4%85%209%20g%20&tag=marcinkorapro-21",
    "youtubePl": "Do małych mechanizmów mam sześć mikroserw MG90S 9 g z metalowymi przekładniami.",
    "youtubeEn": "For small mechanisms I have six 9 g MG90S micro servos with metal gears."
  },
  {
    "id": "gx16",
    "name": "Złącza lotnicze GX16 — 2–8 pinów",
    "short": "Metalowe, rozłączalne połączenia w maszynie CNC",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Używam",
    "price": "£4.75 / zestaw 6-pin",
    "accent": "slate",
    "spec": "GX16 • warianty 2 / 3 / 4 / 5 / 6 / 8 pinów • wtyk i gniazdo panelowe • metalowa obudowa",
    "url": "https://www.amazon.co.uk/s?k=Z%C5%82%C4%85cza%20lotnicze%20GX16%20%E2%80%94%202%E2%80%938%20pin%C3%B3w%20GX16%20&tag=marcinkorapro-21",
    "youtubePl": "Okablowanie maszyny CNC łączę metalowymi złączami lotniczymi GX16 w kilku wariantach pinów.",
    "youtubeEn": "I connect the CNC machine wiring with metal GX16 aviation connectors in several pin-count variants."
  },
  {
    "id": "hcsr04",
    "name": "HC-SR04 — czujnik ultradźwiękowy",
    "short": "Prosty pomiar odległości i wykrywanie przeszkód",
    "category": "Sensory",
    "supplier": "Amazon",
    "project": "Roboty mobilne",
    "status": "Mam",
    "accent": "cyan",
    "spec": "Nadajnik i odbiornik ultradźwiękowy • piny VCC / TRIG / ECHO / GND",
    "url": "https://www.amazon.co.uk/s?k=HC-SR04%20%E2%80%94%20czujnik%20ultrad%C5%BAwi%C4%99kowy%20Nadajnik%20i%20odbiornik%20ultrad%C5%BAwi%C4%99kowy%20&tag=marcinkorapro-21",
    "youtubePl": "Do prostego pomiaru odległości mam ultradźwiękowy czujnik HC-SR04.",
    "youtubeEn": "For simple distance measurement I have an HC-SR04 ultrasonic sensor."
  },
  {
    "id": "xl4015",
    "name": "XL4015 — regulowana przetwornica step-down",
    "short": "Zasilanie prototypów z wyższego napięcia",
    "category": "Zasilanie",
    "supplier": "Amazon",
    "project": "Warsztat",
    "status": "Mam",
    "price": "£5.90",
    "accent": "amber",
    "spec": "DC-DC step-down • regulowane wyjście • 5 A / 75 W deklarowane przez sprzedawcę",
    "url": "https://www.amazon.co.uk/s?k=XL4015%20%E2%80%94%20regulowana%20przetwornica%20step-down%20DC-DC%20step-down%20&tag=marcinkorapro-21",
    "youtubePl": "Do obniżania napięcia w prototypach mam regulowaną przetwornicę XL4015, opisaną przez sprzedawcę jako 5 A / 75 W.",
    "youtubeEn": "For stepping voltage down in prototypes I have an adjustable XL4015 converter, seller-rated at 5 A / 75 W."
  },
  {
    "id": "lm2596",
    "name": "LM2596 — regulowana przetwornica buck",
    "short": "Mały moduł do obniżania napięcia",
    "category": "Zasilanie",
    "supplier": "Amazon",
    "project": "Warsztat",
    "status": "Mam",
    "price": "£2.35",
    "accent": "amber",
    "spec": "DC-DC step-down • regulowane napięcie wyjściowe • moduł LM2596",
    "url": "https://www.amazon.co.uk/s?k=LM2596%20%E2%80%94%20regulowana%20przetwornica%20buck%20DC-DC%20step-down%20&tag=marcinkorapro-21",
    "youtubePl": "Do prostych układów zasilania używam małej, regulowanej przetwornicy buck LM2596.",
    "youtubeEn": "For simple power circuits I use a small adjustable LM2596 buck converter."
  },
  {
    "id": "hc05",
    "name": "HC-05 / HC-06 — Bluetooth UART",
    "short": "Bezprzewodowe połączenie szeregowe z mikrokontrolerem",
    "category": "Sterowanie",
    "supplier": "Amazon",
    "project": "Uniwersalne",
    "status": "Mam",
    "accent": "green",
    "spec": "Bluetooth • interfejs UART • płytka 4-pinowa",
    "url": "https://www.amazon.co.uk/s?k=HC-05%20%2F%20HC-06%20%E2%80%94%20Bluetooth%20UART%20Bluetooth%20&tag=marcinkorapro-21",
    "youtubePl": "Do prostego bezprzewodowego połączenia szeregowego mam moduły Bluetooth HC-05 / HC-06.",
    "youtubeEn": "For simple wireless serial links I have HC-05 / HC-06 Bluetooth modules."
  },
  {
    "id": "ssr-relay",
    "name": "Moduły SSR 5 V — 1 / 2 / 4 / 8 kanałów",
    "short": "Bezgłośne przełączanie pompek w starej fontannie",
    "category": "Sterowanie",
    "supplier": "Amazon",
    "project": "Fontanna",
    "status": "Używałem",
    "accent": "green",
    "spec": "Przekaźniki półprzewodnikowe • sterowanie 5 V • warianty 1 / 2 / 4 / 8 kanałów",
    "url": "https://www.amazon.co.uk/s?k=Modu%C5%82y%20SSR%205%20V%20%E2%80%94%201%20%2F%202%20%2F%204%20%2F%208%20kana%C5%82%C3%B3w%20Przeka%C5%BAniki%20p%C3%B3%C5%82przewodnikowe%20&tag=marcinkorapro-21",
    "youtubePl": "W dawnym projekcie fontanny moduły SSR 5 V przełączały małe pompki sterowane przez ESP.",
    "youtubeEn": "In an earlier fountain project, 5 V SSR modules switched small pumps controlled by an ESP board."
  },
  {
    "id": "lcd1602",
    "name": "LCD 1602 I²C — niebieski, 16×2",
    "short": "Jeden z moich pierwszych wyświetlaczy znakowych",
    "category": "Wyświetlacze",
    "supplier": "Amazon",
    "project": "Uniwersalne",
    "status": "Używałem",
    "accent": "cyan",
    "spec": "16×2 znaki • niebieskie podświetlenie • interfejs I²C",
    "url": "https://www.amazon.co.uk/s?k=LCD%201602%20I%C2%B2C%20%E2%80%94%20niebieski%2C%2016%C3%972%2016%C3%972%20znaki%20&tag=marcinkorapro-21",
    "youtubePl": "Jednym z moich pierwszych wyświetlaczy był niebieski LCD 1602 z interfejsem I²C.",
    "youtubeEn": "One of my first displays was a blue 1602 character LCD with an I²C interface."
  },
  {
    "id": "switch-ip67",
    "name": "Przycisk stalowy LED — 18 mm, IP67",
    "short": "Podświetlany włącznik panelowy do obudów",
    "category": "Sterowanie",
    "supplier": "Amazon",
    "project": "Uniwersalne",
    "status": "Mam",
    "accent": "slate",
    "spec": "18 mm • 12 / 24 V • IP67 • czerwona dioda LED • chromowana obudowa • ON/OFF",
    "url": "https://www.amazon.co.uk/s?k=Przycisk%20stalowy%20LED%20%E2%80%94%2018%20mm%2C%20IP67%2018%20mm%20&tag=marcinkorapro-21",
    "youtubePl": "Do obudów i paneli mam stalowy przycisk ON/OFF 18 mm z czerwoną diodą LED i klasą IP67.",
    "youtubeEn": "For enclosures and panels I have an 18 mm steel ON/OFF button with a red LED and IP67 rating."
  },
  {
    "id": "drag-chain",
    "name": "Prowadnik kablowy do CNC",
    "short": "Ochrona przewodów poruszających się razem z osiami",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Używam",
    "accent": "slate",
    "spec": "Łańcuch kablowy • warianty rozmiarów z serii 7×7 do 15×30 mm • prowadzenie przewodów osi",
    "url": "https://www.amazon.co.uk/s?k=Prowadnik%20kablowy%20do%20CNC%20%C5%81a%C5%84cuch%20kablowy%20&tag=marcinkorapro-21",
    "youtubePl": "Przewody ruchomych osi frezarki prowadzę w elastycznym prowadniku kablowym.",
    "youtubeEn": "I route the moving-axis wiring of the CNC router through a flexible cable drag chain."
  },
  {
    "id": "endstop-led",
    "name": "Mechaniczna krańcówka z diodą LED",
    "short": "Czujnik końca zakresu osi CNC",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "accent": "red",
    "spec": "Mikroprzełącznik mechaniczny • wskaźnik LED • moduł do CNC i drukarek 3D",
    "url": "https://www.amazon.co.uk/s?k=Mechaniczna%20kra%C5%84c%C3%B3wka%20z%20diod%C4%85%20LED%20Mikroprze%C5%82%C4%85cznik%20mechaniczny%20&tag=marcinkorapro-21",
    "youtubePl": "Do wykrywania końca zakresu osi mam mechaniczne moduły krańcówek ze wskaźnikiem LED.",
    "youtubeEn": "For axis travel limits I have mechanical endstop modules with LED indication."
  },
  {
    "id": "laser-650",
    "name": "Moduł lasera czerwonego 650 nm — 5 mW",
    "short": "Linia, punkt lub krzyż do pozycjonowania",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Używam",
    "accent": "red",
    "spec": "650 nm • 5 mW deklarowane przez sprzedawcę • 5 V • regulowana soczewka • linia / punkt / krzyż",
    "url": "https://www.amazon.co.uk/s?k=Modu%C5%82%20lasera%20czerwonego%20650%20nm%20%E2%80%94%205%20mW%20650%20nm%20&tag=marcinkorapro-21",
    "youtubePl": "Do pozycjonowania przy maszynie używam czerwonego modułu laserowego 650 nm z regulowaną soczewką.",
    "youtubeEn": "For machine positioning I use a red 650 nm laser module with an adjustable lens."
  },
  {
    "id": "tr8x8-600",
    "name": "Śruba trapezowa TR8×8 — 600 mm",
    "short": "Napęd liniowy osi z mosiężną nakrętką",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£16.99",
    "accent": "red",
    "spec": "Średnica 8 mm • skok gwintu 2 mm • posuw 8 mm • długość 600 mm • mosiężna nakrętka kołnierzowa",
    "url": "https://www.amazon.co.uk/s?k=%C5%9Aruba%20trapezowa%20TR8%C3%978%20%E2%80%94%20600%20mm%20%C5%9Arednica%208%20mm%20&tag=marcinkorapro-21",
    "youtubePl": "Do napędu liniowego osi mam śrubę trapezową TR8×8 o długości 600 mm z mosiężną nakrętką kołnierzową.",
    "youtubeEn": "For linear axis drive I have a 600 mm TR8×8 lead screw with a flanged brass nut."
  },
  {
    "id": "sanding-belts",
    "name": "Pasy ścierne 50 × 686 mm — P120 / P180",
    "short": "Materiały do szlifierki taśmowej",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Warsztat",
    "status": "Używałem",
    "price": "£11.85 / 10 pasów",
    "accent": "slate",
    "spec": "50 × 686 mm • 5× P120 • 5× P180",
    "url": "https://www.amazon.co.uk/s?k=Pasy%20%C5%9Bcierne%2050%20%C3%97%20686%20mm%20%E2%80%94%20P120%20%2F%20P180%2050%20%C3%97%20686%20mm%20&tag=marcinkorapro-21",
    "youtubePl": "Do wykańczania elementów używałem pasów ściernych 50 × 686 mm w gradacjach P120 i P180.",
    "youtubeEn": "For finishing parts I used 50 × 686 mm sanding belts in P120 and P180 grits."
  },
  {
    "id": "vbit-60",
    "name": "Frez V 60° — trzpień 6 mm",
    "short": "Rowki, fazowanie i grawerowanie w drewnie",
    "category": "CNC",
    "supplier": "Amazon",
    "project": "Frezarka CNC",
    "status": "Mam",
    "price": "£4.84",
    "accent": "red",
    "spec": "Trzpień 6 mm • średnica robocza 32 mm • kąt 60°",
    "url": "https://www.amazon.co.uk/s?k=Frez%20V%2060%C2%B0%20%E2%80%94%20trzpie%C5%84%206%20mm%20Trzpie%C5%84%206%20mm%20&tag=marcinkorapro-21",
    "youtubePl": "Do rowków, fazowania i grawerowania mam frez V 60° z trzpieniem 6 mm i średnicą roboczą 32 mm.",
    "youtubeEn": "For grooves, chamfers and engraving I have a 60° V-bit with a 6 mm shank and 32 mm cutting diameter."
  },
  {
    "id": "anycubic-mono2",
    "name": "ANYCUBIC Photon Mono 2 — drukarka żywiczna",
    "short": "Archiwalna drukarka 4K+, obecnie uszkodzona",
    "category": "Druk 3D",
    "supplier": "Amazon",
    "project": "Druk 3D",
    "status": "Archiwum",
    "price": "£159.00",
    "accent": "violet",
    "spec": "Ekran mono 4K+ • pole robocze 165 × 89 × 143 mm • obecnie uszkodzona",
    "url": "https://www.amazon.co.uk/s?k=ANYCUBIC%20Photon%20Mono%202%20%E2%80%94%20drukarka%20%C5%BCywiczna%20Ekran%20mono%204K%2B%20&tag=marcinkorapro-21",
    "youtubePl": "Do prototypów używałem drukarki żywicznej ANYCUBIC Photon Mono 2; obecnie jest uszkodzona i pozostaje częścią archiwum projektu.",
    "youtubeEn": "I used an ANYCUBIC Photon Mono 2 resin printer for prototypes; it is currently broken and remains part of the project archive."
  },
  {
    "id": "anycubic-resin",
    "name": "ANYCUBIC — czarna żywica roślinna, 2 kg",
    "short": "Materiał do wcześniejszych wydruków żywicznych",
    "category": "Druk 3D",
    "supplier": "Amazon",
    "project": "Druk 3D",
    "status": "Używałem",
    "price": "£35.00 / 2 kg",
    "accent": "violet",
    "spec": "Żywica roślinna • kolor czarny • zestaw 2 kg • druk SLA / LCD",
    "url": "https://www.amazon.co.uk/s?k=ANYCUBIC%20%E2%80%94%20czarna%20%C5%BCywica%20ro%C5%9Blinna%2C%202%20kg%20%C5%BBywica%20ro%C5%9Blinna%20&tag=marcinkorapro-21",
    "youtubePl": "Do wcześniejszych wydruków żywicznych używałem czarnej żywicy roślinnej ANYCUBIC w zestawie 2 kg.",
    "youtubeEn": "For earlier resin prints I used a 2 kg set of black ANYCUBIC plant-based resin."
  }
];
